### ISSUE TITLE
CanUserAddRows="False" disables filtering

### ISSUE THREAD

**Issue by kevbro02** [macgile/DataGridFilter#103]
If I set CanUserAddRows to false, the filter button is no longer available.

**Comment by kevbro02** [comment]
Looks like the issue is related to 'OnItemSourceChanged'. I Bind to an empty observablecollection and fill it later. So my ItemsCount=0 if there is no 'NewItemPlaceHolderItem' in the collection when OnItemsSourceChanged is called (as is the case when CanUserAddRows=False). In this state, GenerateCustomColumns never gets called and the headertemplate is never set.

**Comment by macgile** [comment]
I don't see this, do you have any other details?

**Comment by kevbro02** [comment]
I posted a comment after I saw what was going on. It seemed that there was an assumption that the bound collection would have items in it at the time of binding. I don’t remember exactly, but I there is a check on the count and if count=0 an initialization method didn’t run. My comment spelled it out better than this. Thanks for the reply Sent from Mail for Windows From: macgileSent: Sunday, May 7, 2023 6:22 AMTo: macgile/DataGridFilterCc: kevbro02; AuthorSubject: Re: [macgile/DataGridFilter] CanUserAddRows="False" disables filtering (Issue #103) I don't see this, do you have any other details?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
