### ISSUE TITLE
Special characters removed in popup

### ISSUE THREAD

**Issue by Angyro** [macgile/DataGridFilter#105]
My ItemsSource contains texts with '_' char and it was removed from the popup list.

The code to fix it for my case: It's not nice and universal but I want to share it:

> string val = "";
> if (values[0].ToString() == "{0}" && values[1].ToString().Contains('_'))
> {
>     val = values[1].ToString().Replace("_", "__");
>     return val;
> }

Let me know a better solution.
Thanks for your work!

**Comment by BEDIRHANSAMSA** [comment]
I can confirm this bug, I will try to solve it.
![image](https://user-images.githubusercontent.com/44173331/233189838-47086fac-2c9d-44c9-a20c-1ecbd154b490.png)
