### ISSUE TITLE
Feature request: Saving and resetting filters

### ISSUE THREAD

**Issue by ericvdberge** [macgile/DataGridFilter#108]
Hi all,

I am working on a project, where it would be nice to save the filters that are currently selected. I can then save and load filter presets, which is nice to have in certain use-cases.

Currently, it was easy to get the filters by creating a public property for the criteria list. But when I try to set the criteria list again. It is not updating all the filters and the view again. Can anybody help me with this implementation?

Currently, I edited something like this in the `Filterdatagrid.cs`:
```cs
public Dictionary<string, Predicate<object>> Filters
{
    get => criteria;
    set
    {
        // reset criteria List
        criteria.Clear();
        GlobalFilterList.Clear();
        
        criteria = value;

        CollectionViewSource = System.Windows.Data.CollectionViewSource.GetDefaultView(ItemsSource);
        if (CollectionViewSource.CanFilter) CollectionViewSource.Filter = Filter;
        CollectionViewSource.Refresh();


        OnPropertyChanged(nameof(Filters));
    }
}
```
I can get the filters by requesting `FilterDataGrid.Filters`, but when setting, it will not work.

**Comment by macgile** [comment]
Hi

How it works ?

**Comment by macgile** [comment]
How can I help you then?

**Comment by macgile** [comment]
To understand how it works you can read the article I wrote

**Comment by ericvdberge** [comment]
Do you have time to implement or start implenting this feature? I thought the solution to be as follows: 
We need a public property like 'Filters' that just gets all the filters that are set, maybe with or without the predicate. I can implement the storing by myself. I then need a way to set the Filter property again with the saved filters and the view should be rerendered.
I was thinking that i could just json serialize the filters into a json file on storing and deserialising on reading the file again. Maybe if you have time to start, I can finish the future if I understand the start of the code. Is that possible?

**Comment by BEDIRHANSAMSA** [comment]
I can contirbute this

**Comment by ericvdberge** [comment]
I have an idea, but I just can't get it to work. I am working a few days on this already, but the code is hard to understand.

I will get straight to the point. 
- `The criteria list should not be in the filterdatagrid.cs file`. I think every filtercommon class should have a criteria list, because the global criteria list is also seperated by fieldname by using the dictionary and key. The filter function (from the datagrid view) should then be adapted to get all criteria from all globalListFilters by doing a `GlobalFilterList.SelectMany(f => f.Criteria)`.
- The dependency property should be a list of Filtercommons.

And when setting the filterpreset dependencyproperty, we should render all the filters in the datagrid. 
Can you help me making this implementation? I think that this is all that we need, but I cannot get it to work.
