### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by FERROUSSAGE** [macgile/DataGridFilter#111]
Good afternoon
I ran into a problem that the filter does not work, although I do everything according to the instructions. I am attaching screenshots
![image](https://user-images.githubusercontent.com/42603722/237033695-9ed8d1e6-4adf-44ce-911f-794c596498e7.png)
![image](https://user-images.githubusercontent.com/42603722/237033749-11c1b5cd-47f7-4a86-9ca5-7960645636d6.png)
![image](https://user-images.githubusercontent.com/42603722/237033791-ae16f789-6ba2-4aa8-b72a-ccd8fe588a67.png)
What could be the problem?

**Comment by RejeanLabbe** [comment]
I have the same problem. @FERROUSSAGE how did you solve this?

**Comment by macgile** [comment]
Which version ?

**Comment by RejeanLabbe** [comment]
@macgile I use version 1.2.7 with .NET Framework 4.8

![image](https://github.com/macgile/DataGridFilter/assets/5299301/7841eb1a-76e8-4cf6-8ecd-6e2a86c8912a)

The grid is displayed and columns are sorting, the status bar is also shown, but filter icons are missing.

Here is my XAML code

```

<fdg:FilterDataGrid
					x:Name="lvAnalyses"
					Grid.Row="2"
					Margin="10,10,0,2"
					AlternatingRowBackground="WhiteSmoke"
					AlternationCount="2"
					AutoGenerateColumns="False"
					Background="Transparent"
					CanUserAddRows="False"
					ColumnWidth="*"
					DateFormatString="d"
					FilterLanguage="French"
					HorizontalGridLinesBrush="LightGray"
					IsReadOnly="True"
					ItemsSource="{Binding ListeAnalyses, UpdateSourceTrigger=PropertyChanged}"
					RowHeaderWidth="40"
					ShowElapsedTime="True"
					ShowStatusBar="True"
                        LoadingRow="DataGrid_LoadingRow"
					VerticalGridLinesBrush="LightGray"
					VerticalScrollBarVisibility="Visible"
					VirtualizingStackPanel.IsVirtualizing="True">


                        <fdg:FilterDataGrid.Columns>
                            

                            <fdg:DataGridTextColumn
						Binding="{Binding CodeLieu}"
						Header="Lieu"
						Width="50"
						IsColumnFiltered="True" />

                            <fdg:DataGridTextColumn
						Binding="{Binding IdAnalyse}"
						Header="Id Analyse"
						Width="100"
						IsColumnFiltered="True" />

                            <fdg:DataGridTextColumn
						Binding="{Binding IdAnalyseUnifie}"
						Header="ID Unifié"
						Width="100"
						IsColumnFiltered="True" />

                            <fdg:DataGridTextColumn
						Binding="{Binding Revision}"
						Header="Révision"
						Width="60"
						IsColumnFiltered="True" />
                        </fdg:FilterDataGrid.Columns>
                    </fdg:FilterDataGrid>

```

I use this in combination with Exceed Toolkit BusyIndicator control. Maybe this is not compatible. I'll make more tests.

**Comment by macgile** [comment]
what does this LoadingRow="DataGrid_LoadingRow" method do?

**Comment by RejeanLabbe** [comment]
I copied this from the example on CodeProject

```
private void DataGrid_LoadingRow(object sender, DataGridRowEventArgs e)
        {
            var index = e.Row.GetIndex() + 1;
            e.Row.Header = $"{index}";
        }
```

I removed the **LoadingRow** parameter but it doesn't change anything.

**Comment by RejeanLabbe** [comment]
When I copy the CodeProject example, it works, so it looks like I'm doing something wrong.

**Comment by macgile** [comment]
Finally everything is good then !
