### ISSUE TITLE
 Add columns dynamically, filter not working

### ISSUE THREAD

**Issue by FERROUSSAGE** [macgile/DataGridFilter#112]
Hi all!
I'll ask the last question, otherwise I spammed something.

Is it possible to somehow set the default filter on all columns?

The fact is, I have a dynamic datagrid and columns are added dynamically at the request of the user.

When adding a new column, the filter is not enabled, although the IsColumnFiltered attribute is specified.

So the question is, is there any way I can put this attribute by default so that the filter is always there?

**Comment by macgile** [comment]
Hi,

You can even try to do it from the source code.
Get back to me to see if it works.
