### ISSUE TITLE
Header buttons display problem on ArcGIS Pro add-in

### ISSUE THREAD

**Issue by RejeanLabbe** [macgile/DataGridFilter#117]
There is strange behaviour when using DataGridFilter on an ArcGIS Pro window : Header buttons icons are bigger and the borders are missing.

![image](https://github.com/macgile/DataGridFilter/assets/5299301/4ffe21aa-07b8-42d2-bc4c-3284e3eeb01b)

instead of

![image](https://github.com/macgile/DataGridFilter/assets/5299301/ffc1a25e-a3b1-4f8b-88dd-e9c9b11efea7)

@macgile Do you have any idea?

**Comment by macgile** [comment]
Which version are you using?
Since version 1.2.6 the button design has changed

**Comment by RejeanLabbe** [comment]
My bad. I was comparing version 1.2.3 in the CodeProject example with version 1.2.7.

Thanks
