### ISSUE TITLE
Adding items to the ItemsSource of the datagrid doesnt update Status bar

### ISSUE THREAD

**Issue by melsawy93** [macgile/DataGridFilter#123]
Hi, When modifying by adding or removing items from the ItemsSource of the datagrid, the status row isnt refreshed.

2 record(s) found on 2

Adding a row:

3 record(s) found on 2

**Comment by macgile** [comment]
Hi,
what method do you use to refresh the source?

**Comment by melsawy93** [comment]
My itemssource is bound to an observablecollection and Im just using .add to add items to it.

**Comment by macgile** [comment]
Hi,
Use you in ItemsSource: UpdateSourceTrigger=PropertyChanged ?

**Comment by melsawy93** [comment]
Yep, I managed to solve it b ut I had to modify your code. I will post a pull request later if you would like.

**Comment by macgile** [comment]
Yes thanks
best regards
