### ISSUE TITLE
Transparent window makes popup transparent

### ISSUE THREAD

**Issue by MichaelInkster** [macgile/DataGridFilter#124]
If the parent window is transparent, the popup window becomes transparent.
Can the background be changed to inherit from the FilterDataGrid rather than the Window?

**Comment by KC-MarKamp** [comment]
Hi @MichaelInkster, I'm currently working on it! I'm making a property for it, so you can set the color yourself from within the control :)

**Comment by macgile** [comment]
Hi,

I merged your contribution

best regards

**Comment by KC-MarKamp** [comment]
Hi @macgile, thanks! Happy to help! Perhaps the other issue regarding to the background, Issue #122, can also be closed with this PR :)

**Comment by macgile** [comment]
Hi,
Changing the background color was already a user request.
I cannot accommodate all requests for design changes.
I also want to keep the configuration by DependencyProperty as simple as possible, they should not multiply
