### ISSUE TITLE
Drop support for out-of-support .NET runtimes (.NET Core 3.1 and .NET 5)

### ISSUE THREAD

**Issue by Styxxy** [macgile/DataGridFilter#127]
Drop support for out-of-support (end-of-life) .NET runtime version. In this case:
* .NET Core 3.1
* .NET 5

![End-of-life .NET versions](https://github.com/macgile/DataGridFilter/assets/1635825/83ff25a6-0854-4321-84ed-d64b51acec61)

See also: https://github.com/dotnet/core/blob/main/releases.md

**Comment by macgile** [comment]
thanks for the information !
