### ISSUE TITLE
If there are empty values in a column, filter the empty values first, and then filter the other values. The previous step filter null value will fail!!!

### ISSUE THREAD

**Issue by ReverseLw** [macgile/DataGridFilter#128]
I'm going to change that question
![image](https://github.com/macgile/DataGridFilter/assets/105032471/7fe25b56-127d-41ed-be0b-d2e3149f02a8)
In the FilterDataGrid.cs class
![image](https://github.com/macgile/DataGridFilter/assets/105032471/290a2a1a-fefe-4b54-8ed6-28aa711be92e)

**Comment by macgile** [comment]
Hi,
You are using an old version, look at the code for version 1.2.8 please

**Comment by ReverseLw** [comment]
I did find this problem in version 1.28
