### ISSUE TITLE
No Filter with Dynamically created DataGrid and ItemSource

### ISSUE THREAD

**Issue by Roneri75** [macgile/DataGridFilter#132]
So i have a WPF app that i'm doing for internal use only to post queries agains an api where you can ask the api for the input an putout fields for any api.
So I can query one API for all other API to get both the input and put fields.
And in this app i want to show the output data as a datagrid and I would like to filter and sort the datagrid to be able to see what the result output is.
So I though i test this grid to see if it would do the trick for me.
Currently I create the grid first programmatically, to be able to see all output columns, and then, if the user chooses to, can post the query to the API and see the result. So i create a DataTable that I Binde "manually" in code when I post the query.
I set the column for the DataTable and DataGridTextColumn, programmatically, and creates the rows.
Should this work, theoretically with this FilterDataGrid?
I'm not getting the filter to work but the sorting works.
Is there a trick to get the filter to work, or do I have to make the DataTable like an ObservableCollection or do I have to some how "refesh" the filer mechanism of the Filter DataGrid some how to make the Filter work some how?
This is the code in the Xaml for the DataGrid
```
        <control:FilterDataGrid
            x:Name="OutputDataGrid"
            Grid.Column="1"
            AutoGenerateColumns="False"
            DateFormatString="d"
            FilterLanguage="English"
            ShowElapsedTime="False"
            ShowRowsCount="True"
            ShowStatusBar="True">
        </control:FilterDataGrid>
```
And this is roughly how I create the DataGrid columns.
I do add an Tooptip to the DataGrid HeaderColumn, but that should not cause any problems right?
 
```
        private void AddColumnWithTooltip(DynamicTabUC dynamicTabUC, string headerText, string bindingPath, string tooltipText)
        {

            FilterDataGrid.DataGridTextColumn textColumn = new FilterDataGrid.DataGridTextColumn
            {
                Header = headerText,
                Binding = new Binding(bindingPath)
            };

            // Create the template using XamlReader
            string xamlTemplate = $@"
        <DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'>
            <ContentControl Content='{{Binding}}'>
                <ContentControl.ToolTip>
                    <ToolTip Content='{tooltipText}' />
                </ContentControl.ToolTip>
            </ContentControl>
        </DataTemplate>";

            DataTemplate headerTemplate = (DataTemplate)XamlReader.Parse(xamlTemplate);

            Style headerStyle = new Style(typeof(DataGridColumnHeader));
            headerStyle.Setters.Add(new Setter(ContentControl.ContentTemplateProperty, headerTemplate));

            textColumn.HeaderStyle = headerStyle;
            textColumn.Width = DataGridLength.Auto;
            textColumn.IsColumnFiltered = true;
            textColumn.IsReadOnly = true;

            dynamicTabUC.OutputDataGrid.Columns.Add(textColumn);
        }
```
dynamicTabUC is my User Control where the FilterDataGrid, named OutputDataGrid exists.
After this is done I can create my datatable with the columns that will then be set as the ItemSouce to this datagrid and it will binde the columns in the DataTable to the column.
And it all works good except for the fact that I don't the filer onthe columns.

Any information or ides on how to make this work would be appreciated!

**Comment by macgile** [comment]
Hi,

according to your code, is the column added to your filterdatagrid OutputDataGrid?

**Comment by Roneri75** [comment]
Yes it is, and and said, everything seems to work just fine except for the Filtering that does not pop up.

**Comment by macgile** [comment]
Try with a second column, one using the normal operation of the Filterdatagrid including the XAML
and the other added by the code, see what happens.

Don't forget that you must provide the filterdatagrid with a collection, in your code I don't see it including in the xaml.

**Comment by macgile** [comment]
In the "normal" operation of filtardatagrid, the columns are constructed from the fields of the collection, they are filtered if the "IsColumnFiltered" property is set to true, the filter template is applied to these columns.

**Comment by Roneri75** [comment]
Okay so the problem might be that I'm creating the Headers first, without a ItemSource and then, if user choose to, the ItemSource is then "bound" to the DataGrid.
So maybe that is the problem that the ItemSource is not there when the Columns are greated?
But just so I understand, it should not be a problem to use a DataTable as an ItemSources in general?

**Comment by macgile** [comment]
Hi,
I don't know, I haven't tested it yet
