### ISSUE TITLE
Filters will be stuck if all rows are deleted

### ISSUE THREAD

**Issue by bakioztepe** [macgile/DataGridFilter#139]
After some filters are applied, and a few rows are being displayed, if all of the rows are deleted (from ItemsSource), filters will be stuck and the popup windows cannot be opened. The only solution is to press "Remove all filters" button. 

There should be a way to change the filters, if nothing is left to display. Or "Remove all filters" can be called automatically.

**Comment by macgile** [comment]
Hi,
Yes, it's a problem, I'll fix it

best regards

**Comment by macgile** [comment]
Hi,

fixed in next commit


best regard
