### ISSUE TITLE
autogenerate columns problem

### ISSUE THREAD

**Issue by sperlukh** [macgile/DataGridFilter#149]
hi.
i have such problem:
when i set AutoGenerateColumns = true and set .ItemsSource = items (ienumerable <class>)  - works excilent
but 
when i set AutoGenerateColumns = true and set .ItemsSource = datatable.DefaultView - do not works, filter symbols i see but they do not work.

remarks: i create datagrid in code: FilterDataGrid.FilterDataGrid newDataGrid = new FilterDataGrid.FilterDataGrid() and then 
                    newDataGrid.ShowStatusBar  = true;
                    newDataGrid.ShowRowsCount = true;
                    newDataGrid.ClipboardCopyMode = DataGridClipboardCopyMode.IncludeHeader;
                    newDataGrid.IsReadOnly = true;
                    newDataGrid.FilterLanguage = FilterDataGrid.Local.English;
                    newDataGrid.AutoGenerateColumns = true;
                    newDataGrid.CanUserAddRows = false;
                    newDataGrid.ExcludeFields = "";
                    newDataGrid.ItemsSource = GetTable().DefaultView;

**Comment by sperlukh** [comment]
version 1.2.7

**Comment by macgile** [comment]
Hi,

This is a problem that has already been mentioned, unfortunately I don't have a solution for the moment.
