### ISSUE TITLE
Filter not working with single string and DataGridTextColumn

### ISSUE THREAD

**Issue by Apflkuacha** [macgile/DataGridFilter#15]
When using the FilterDataGrid with a simple binding to a string List like: `IEnumerable<string> VariableList { get; set; } = new string[] { "Variable1", "any other variable" };`
And using following definition in MainWindow, it doesn't work to load the Filter.

    <FilterDataGrid:FilterDataGrid ItemsSource="{Binding VariableList}" AutoGenerateColumns="False">
        <FilterDataGrid:FilterDataGrid.Columns>
            <FilterDataGrid:DataGridTextColumn Binding="{Binding}" Header="Variable Names" IsColumnFiltered="True" />
        </FilterDataGrid:FilterDataGrid.Columns>
    </FilterDataGrid:FilterDataGrid>`

**Comment by macgile** [comment]
It is not possible to use filters with a collection without fields, because it is thanks to them that the filters work.
