### ISSUE TITLE
Externally applied filter override

### ISSUE THREAD

**Issue by KansaraMaulik** [macgile/DataGridFilter#150]
I have used filterdatagrid in MainWindow where i have applied filter which i want as a default filter to be applied with other selected filters.

but due to line written below, it is being overridden on Itemsource change

 // set Filter, contribution : STEFAN HEIMEL
                if (CollectionViewSource.CanFilter) CollectionViewSource.Filter = Filter;

**Comment by macgile** [comment]
Hi,
You didn't give me enough information to understand your problem

**Comment by KansaraMaulik** [comment]
Basically, I am using CollectionViewSource for FIlterDataGrid. This collections contains all records including Active and deleted records.

Now I want to show only active records and i do not want to allow user to filter records based on status. 

My application support multi view interface and new records in collectionViewSource will keep adding/updating.

to achieve this, I need an option where i can prepare a custom filter(predicate) which I can bind with Filterdatagrid. so that, this custom filter should work along with filters applied through control (criteria). 

I tried to bind the filter but it is replaced due to line written below

// set Filter, contribution : STEFAN HEIMEL
if (CollectionViewSource.CanFilter) CollectionViewSource.Filter = Filter;

**Comment by macgile** [comment]
What you are asking me is not possible in the sense that "CollectionViewSource.Filter = Filter;" is the heart of datagrid filtering, without it the filters activated by the user on the columns no longer work.
The solution for you would be to use a filter on the source collection to hide the records that you do not want to appear in the datagrid, a bit like the demo application which allows you to filter the collection before being provided to the datagrid. “itemsSource” property of “FilterDatagrid”.

**Comment by KansaraMaulik** [comment]
HI,
Actually it is possible. I have applied the changes in FilterDataGrid.cs and external filters are working for me along with criteria. I can raise PR If you want to include that feature.

**Comment by KansaraMaulik** [comment]
PR #151 raised.
