### ISSUE TITLE
Adding a Hebrew translation

### ISSUE THREAD

**Issue by abaye123** [macgile/DataGridFilter#152]
Hi, I'm using it and it's very good, I want to add a Hebrew language translation to it, how can we do that? I can translate the strings from English myself

**Comment by macgile** [comment]
Hi,
No problem, it's in the Loc.cs file
  Look for the block of code that begins with "ILanguageDictionary English { get; } = new LanguageDictionary("English", new CultureInfo("en-US") ..............."

best regards

**Comment by macgile** [comment]
Hi,
Than's for your contribution :)

Best regards
