### ISSUE TITLE
Scrolling with grouped elements is not smooth

### ISSUE THREAD

**Issue by Daedalin** [macgile/DataGridFilter#153]
Hello I use a grid in one of my private projects.
So far it works very well.
I use the standard way of grouping columns. unfortunately, you can't scroll so nicely with your grid. 

on the left is the normal DataGrid on the right is your FilterGrid.

https://github.com/macgile/DataGridFilter/assets/57679443/86882f50-3e19-4808-98e0-0fbc466b10ce

The gif comes from a small test programm in which I placed the two grids next to each other.
https://github.com/Daedalin/FilterDataGrid_Scrolling_Bug

**Comment by macgile** [comment]
Hi,

Indeed there is a problem, I will modify the "FilterDataGrid" template to correct it.
In the meantime, you can modify the code yourself in Generic.xaml file.

`
  
                            <ScrollViewer  
                                x:Name="DG_ScrollViewer"  
                                Grid.Row="0"  
                                CanContentScroll="True"  
                                Focusable="false">
`  
become
`
  
                            <ScrollViewer  
                                x:Name="DG_ScrollViewer"  
                                Grid.Row="0"  
                                Focusable="false">
`

**Comment by Daedalin** [comment]
@macgile 
Hello thank you for the quick response and I have also seen that they have already adjusted the problem in the code.

Unfortunately I don't quite understand their intermediate solution because this is in their source code and not in mine.

Can you tell me when you want to publish the changes via .nuget package?
