### ISSUE TITLE
Request for Search String Retrieval Property

### ISSUE THREAD

**Issue by alcsdn** [macgile/DataGridFilter#157]
Hello,

I am currently using DataGridFilter in my WPF project to implement a DataGrid with filtering capabilities. However, I've encountered a limitation: I need a way to retrieve the  '**search**' string entered by the user in the search text block so that I can utilize it within my ViewModel. This functionality is crucial for my project as I need to utilize the string for further processing within my application logic.

**Feature Request:**
I kindly request the addition of a feature that allows access to the search text input by the user in the search box of the DataGrid column. This would enable developers to retrieve the search string from the DataGrid and utilize it within their ViewModels.

**Use Case Scenario:**
Consider a scenario where a user enters a search query in the search box provided by the DataGrid to filter the displayed data. As a developer, I need to access this search query string from my ViewModel to perform additional operations based on the user's input.

Thank you for considering this enhancement request.

**Comment by macgile** [comment]
Hi alicec88,

This is a specific feature, so I wouldn't integrate it.
However, here is the procedure to follow to implement it yourself from the source code that you will need to compile to use it.

1 )  Declare special EventArgs class to hold information about the request, place it in the FilterItem.cs file

```xml
    /// <summary>
    ///  SearchQueryEventArgs class to hold custom event info
    /// </summary>
    public class SearchQueryEventArgs : EventArgs
    {
        public SearchQueryEventArgs(string fieldName, string query, bool startWith)
        {
            FieldName = fieldName;
            Query = query;
            StartWith = startWith;
        }
        public string FieldName { get; private set; }
        public string Query { get; private set; }
        public bool StartWith { get; private set; }
}
```
2 ) Declare the EventHandler in FilterDataGrid class.

```
 public event EventHandler<SearchQueryEventArgs>  RaiseSearchQueryEvent;
```

3 ) Create a protected invoking method in the FilterDataGrid class
```
        /// <summary>
        /// OnSearchQueryEvent Event invocations
        /// </summary>
        /// <param name="e"></param>
        protected virtual void OnSearchQueryEvent(SearchQueryEventArgs e)
        {
            var raiseEvent = RaiseSearchQueryEvent;
            raiseEvent?.Invoke(this, e);
        }
```
4 ) At the end of the "if(search)" block of the "ApplyFilterCommand" method
```
if (search)
{
      ...
      ...
      OnSearchQueryEvent(new SearchQueryEventArgs(CurrentFilter.FieldName,searchText, startsWith));
}
```
5 ) Final, in your application
```
public partial class MainWindow
 {

        public MainWindow()
        {
            InitializeComponent();
            ....
            FilterDataGrid.RaiseSearchQueryEvent += FilterDataGrid_RaiseSearchQueryEvent;
           ...

        }

        private void FilterDataGrid_RaiseSearchQueryEvent(object sender, FilterDataGrid.SearchQueryEventArgs e)
        {
            Debug.WriteLine($"Field : {e.FieldName, -10}Query : {e.Query, -20} Start With : {e.StartWith}");
        }

}
```

Best regards
