### ISSUE TITLE
Wrap header text

### ISSUE THREAD

**Issue by St1Ff90** [macgile/DataGridFilter#158]
May you please describe how to customize Header Text? All standard ways don't work.

**Comment by macgile** [comment]
Hi,

See this section in Generic.xaml file
    
    <DataTemplate x:Key="DataGridHeaderTemplate">

Best regards

**Comment by St1Ff90** [comment]
> Hi,
> 
> See this section in Generic.xaml file
> 
> ```
>     
>     <DataTemplate x:Key="DataGridHeaderTemplate">
> ```
> 
> Best regards

Thank you for the response! Could you, please, advise how to wrap a header text?
