### ISSUE TITLE
CheckBoxColumn only works with Nullable bool

### ISSUE THREAD

**Issue by Epsilon839** [macgile/DataGridFilter#162]
In FilterDataGrid.OnAutoGeneratingColumn() when checking the property type the check ignores non nullable bools. Which causes the column to default to a textbox column. 

```
		if (e.PropertyType.GenericTypeArguments.FirstOrDefault() == typeof(bool))
			{
				DataGridCheckBoxColumn column2 = new DataGridCheckBoxColumn
				{
					Binding = new Binding(e.PropertyName)
					{
						ConverterCulture = Translate.Culture
					},
					FieldName = e.PropertyName,
					Header = e.Column.Header.ToString(),
					HeaderTemplate = headerTemplate,
					IsColumnFiltered = true
				};
				e.Column = column2;
				return;
			}
```

Maybe 
`		if (e.PropertyType == typeof(bool) || e.PropertyType.GenericTypeArguments.FirstOrDefault() == typeof(bool))`

**Comment by macgile** [comment]
Hi Epsilon839,

Yes, I correct this.

best regards

**Comment by Epsilon839** [comment]
Thank you. I appreciate the work you are doing here.

**Comment by Epsilon839** [comment]
A follow up on this. We ran into a similar issue with nullable Enums. In this case it doesn't work with nullables. 

After looking harder at the code I think what you can do is move the line 

`			fieldType = Nullable.GetUnderlyingType(e.PropertyType) ?? e.PropertyType;`

before 

`			if (e.PropertyType.IsEnum)`

Then in the following type checks, use fieldType for the checks instead of e.PropertyType.

```
if (feildType.IsEnum) ...

if (feildType == typeof(bool))...

if (fieldType == typeof(DateTime) && !string.IsNullOrEmpty(DateFormatString))...
```

**Comment by macgile** [comment]
Hi,
Look at my corrections, that's what I did :)

best regards
