### ISSUE TITLE
Czech Language

### ISSUE THREAD

**Issue by hanyscz** [macgile/DataGridFilter#167]
Could I please request the addition of the Czech language? I can provide the translations. Alternatively, could you add support for external language packs?

private static ILanguageDictionary Czech { get; } = new LanguageDictionary("Czech", new CultureInfo("cs-CZ"),
    new Dictionary<TranslatableElements, string>
    {
        { TranslatableElements.All, "(Vybrat vše)" },
        { TranslatableElements.Empty, "(Prázdné)" },
        { TranslatableElements.Clear, "Vymazat filtr \"{0}\"" },
        { TranslatableElements.Contains, "Hledat (obsahuje)" },
        { TranslatableElements.StartsWith, "Hledat (začíná na)" },
        { TranslatableElements.Toggle, "Přepnout obsahuje/začíná na" },
        { TranslatableElements.Ok, "Ok" },
        { TranslatableElements.Cancel, "Zrušit" },
        { TranslatableElements.Status, "{0:n0} záznam(ů) nalezeno z {1:n0}" },
        { TranslatableElements.ElapsedTime, "Uplynulý čas {0:mm}:{0:ss}.{0:ff}" },
        { TranslatableElements.True, "Zaškrtnuto" },
        { TranslatableElements.False, "Nezaškrtnuto" },
        { TranslatableElements.RemoveAll, "Odebrat všechny filtry" },
        { TranslatableElements.Indeterminate, "Neurčeno" },
    });

**Comment by macgile** [comment]
Hi hanyscz,
Added, thank for your contribution :)

Best regards

**Comment by hanyscz** [comment]
Thank :-)
