### ISSUE TITLE
Filter not working when ItemsSource is of Type DataTable

### ISSUE THREAD

**Issue by Othmane-Ouazzani** [macgile/DataGridFilter#168]
When ItemsSource is DataTable in the DataGrid , the icons don't even show , i managed to tweek the source code a bit to make the Filter visible , but the ListBox comes empty , it works fine for ObservableCollection , converting from DataTable to ObservableCollection  in this case is not a possible solution for me . Hope there's a solution for this , thanks.
![image](https://github.com/macgile/DataGridFilter/assets/56415404/8695505e-1619-405a-8eb6-526dba5e1a96)

**Comment by macgile** [comment]
Hi,

You can't use datatable.DefaultView directly, you need to convert it first.
See this article : https://www.codeproject.com/Articles/846554/Various-Ways-to-Convert-DataTable-to-List

best regards
