### ISSUE TITLE
Output of filtered data

### ISSUE THREAD

**Issue by hanyscz** [macgile/DataGridFilter#173]
Hi, how can I enable getting filtered data into another collection? Is there an output, or is it not possible? Maybe I’m looking at it incorrectly.

**Comment by Basnederveen** [comment]
Have the same question, somehow I would like to bind to the filtered collection in my viewmodel

**Comment by macgile** [comment]
Hi,
You can see demo app

**Comment by Basnederveen** [comment]
I see in the sample app you are binding the 'FilteredList', but the filteredlist is computed in the ViewModel.

I would like the user to use the filter menu's and iterate over what is left in the UI from a command. 

Am I missing something?

**Comment by macgile** [comment]
be more explicit, I don't understand what you want to do, make pseudo code if necessary

**Comment by Basnederveen** [comment]
Thanks for the reply. I see i wasn't very clear in my previous comment ;)

What I mean is, if I have 8 items in my ObservableCollection that is bound to the datagrid, and I filter it down to 2 items by using the popup menu's, how do I access the filtered collection in my viewmodel. 

If I filter the DataGrid, my source still contains 8 items. So if I iterate over my source, also filtered items are returned.

**Comment by macgile** [comment]
Your solution seems correct to me. I agree with you that having to cast the Items collection to get the resulting collection from the filtering is not elegant at all, but I haven't found any other way to do it. If you look at the source code of FilterDataGrid, I call this method several times.

**Comment by macgile** [comment]
I worked for several days to find an alternative and finally I had to resign myself because the code I produced was not more efficient.
