### ISSUE TITLE
Persistent Filter not getting named correctly

### ISSUE THREAD

**Issue by keeday** [macgile/DataGridFilter#174]
Hi,

In the readme it says

> The name of the json file is inferred from the name you give to your FilterDataGrid control.
>If it is not provided, the type name of the source collection is used, for example for a generic list of type Employees, Employees will be used.

However, the persistent filter json is saved with the name `persistentFilter.json` regardless.

I would like to suggest that the `SavePreset()` and `LoadPreset()` could take a string argument, which would represent the name of the file.

E.g;
```C#
MyDataGrid.SavePreset("MyPresetFilter");
MyDataGrid.LoadPreset("MyPresetFilter");
```

Would save and load `MyPresetFilter.json`

This would achieve more control over the persistent filters, and allowing the functionality to have multiple persistent filters setup for a single table.

I would not mind having a go at trying to implement this and submit a pull request.

**Comment by macgile** [comment]
Hi,
The **SavePreset()** and **LoadPreset()** methods work independently of the **PersistentFilter** property, the name is set on the condition that this property is set to True.

```c#
   if (PersistentFilter && collectionType != null)
       fileName = !string.IsNullOrEmpty(Name) ? $"{Name}.json" : $"{collectionType?.Name}.json";
```
I'll remove the condition
