### ISSUE TITLE
Persistentfilter.json access forbidden

### ISSUE THREAD

**Issue by gtomaino** [macgile/DataGridFilter#175]
Hello, when I try to SavePreset or LoadPreset I get a System.UnauthorizedAccessException:
Access to path 'C:\Program Files (x86)\5Space\SmartTrade\persistentFilter.json' forbidden

If I try to run the application as administrator, everything works fine.

**Comment by macgile** [comment]
Hi,
I will fix this problem, in the meantime try setting rights on the folder.
best regards
