### ISSUE TITLE
Search bar + <enter>=ok-button

### ISSUE THREAD

**Issue by delosbomos** [macgile/DataGridFilter#18]
Is it possible to make the 'search (contains)' active after selecting the filter-button in the grid,
so you can start typing immediatly?
It would also be perfect if pressing enter  in the 'search' box would act as pressing the 'ok-button'.

**Comment by macgile** [comment]
It is a good suggestion to put the focus on the search box as well as the ok button.
I would do it on the return of my holidays.
Best regards

**Comment by macgile** [comment]
This is added in the last commit, while waiting for me to update the NuGget package you have to compile the code by yourself, sorry for this inconvenience.

**Comment by delosbomos** [comment]
I downloaded the latest version. The <enter> button activating the ok-button works perfectly.
The focus on the searchtextbox does not seem to work on my computer. Could you please check this?

**Comment by macgile** [comment]
Is fixed

**Comment by delosbomos** [comment]
It works perfect now !!
Thank you so much, very happy with this update ;-)
