### ISSUE TITLE
Error in Generic.xaml disturbs column alignment

### ISSUE THREAD

**Issue by techpara** [macgile/DataGridFilter#180]
I have many tabs on a view each tab has one FilterDataGrid. When tab loads first time no error and everything works fine.

But when I switch tabs it start giving following error and column alignment messed.

![image](https://github.com/user-attachments/assets/bbd6025f-8756-4339-af90-b7a034faf96f)

![image](https://github.com/user-attachments/assets/be4bf835-6492-41c3-89f2-91a0d7968963)

1) Severity	Count	Data Context	Binding Path	Target	Target Type	Description	File	Line	Project
Error	39	null	AreRowDetailsFrozen	DataGridDetailsPresenter.(SelectiveScrollingGrid.SelectiveScrollingOrientation)	SelectiveScrollingOrientation	Cannot find source: RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1'.			

2) Severity	Count	Data Context	Binding Path	Target	Target Type	Description	File	Line	Project
Error	22	null	HeadersVisibility	DataGridRowHeader.Visibility	Visibility	Cannot find source: RelativeSource FindAncestor, AncestorType='System.Windows.Controls.DataGrid', AncestorLevel='1'.	

This column alignment issue can be work around by removing `HeadersVisibility = "Column"` but then one extra column shows on left side. Se image below

![image](https://github.com/user-attachments/assets/8b5c896e-73e7-4e07-9fe0-88b7c61fdfc5)

**Comment by macgile** [comment]
Hi,
From the screenshot you provided, it looks like there are 2 instances of filterdatagrid overlapping each other.
Check your viewmodel code and make sure the page-to-page navigation mechanism is working properly (including the datacontext of each page)

**Comment by macgile** [comment]
Hi,

Ok, I will test your implementation and see what is wrong with the filterdatagrid.

**Comment by macgile** [comment]
Are the contents of your tabs pages or user controls?

**Comment by macgile** [comment]
This dll is missing 
 "xmlns:resources="clr-namespace:Generator.Common.Resources;assembly=Generator.Common""

**Comment by macgile** [comment]
Hi,
In a minimalistic application, and using your style and hierarchical navigation architecture, I have no problem with column shifts
Use snoop to check the visual tree of your application.

![Capture_1](https://github.com/user-attachments/assets/20d72043-4014-4968-9f6a-631b0c7bbab6)  

Project File
[DemoTab.zip](https://github.com/user-attachments/files/17162264/DemoTab.zip)
