### ISSUE TITLE
Null DateTime in Filter Popup

### ISSUE THREAD

**Issue by DanTm99** [macgile/DataGridFilter#182]
Null DateTimes show as 0001 January 01 in the filter popup, despite being blank in the grid. 

Is there any way of having them show as (blank) or (null) in the filter popup? This would also allow the filter to distinguish them from DateTime.MinDate

**Comment by macgile** [comment]
Hi,
The filter handles null Datetime value, if it displays a value it means the date is not null.
DateTime.MinValue is not a date but a Tick value

best regards

**Comment by DanTm99** [comment]
No value is shown in the column itself when the value is null, but the filter popup still shows 0001 January 01 (which isn't shown when the null dates aren't in the source). This seems to imply that the filter popup is seeing null dates as `DateTime.MinValue`.

The xaml for the column looks like below:
```xaml
<control:DataGridTextColumn
    Header="Start Date"
    Binding="{Binding StartDate, Converter={Static Resource MinDateToNullConverter}}"
    IsColumnFiltered="True" />
```

**Comment by macgile** [comment]
This can't work because what you are doing is changing the display not the source, the filter works relative to the source collection.

**Comment by DanTm99** [comment]
Is there any way of having the filter look at the value after it has gone through the converter?

**Comment by macgile** [comment]
Certainly not, all Filterdatagrid logic relies on the data source.
It is up to the developer to provide the right collection.
