### ISSUE TITLE
Problem removing column filter (only if the idea of ​​Datagrid is to reproduce Excel's behavior)

### ISSUE THREAD

**Issue by contagrrla1234** [macgile/DataGridFilter#183]
Hello,

I was using your Datagrid and discovered that your control does not behave like Excel. Was the goal of your Datagrid to reproduce Excel's behavior?

Here I show how they are different:

![removefilter](https://github.com/user-attachments/assets/4835cc14-fce1-4592-8f5f-caf30b4c62b4)

After adding a filter to a column, adding a second filter to a second column and finally removing the filter from the first, the remaining filter does not retain the values ​​from when it was created.

Here is the comparison between your Datagrid and Excel:

![removefilter](https://github.com/user-attachments/assets/f2fae8ad-f208-44ec-86ba-cee44bb12c2f)

**Comment by macgile** [comment]
Hi,

Yes, there is a difference, it does not exactly reproduce the behavior of the excel filter
You can use the beta version of "FilterDatagrid" which works identically to Excel, this version is not guaranteed for production.

best regards
