### ISSUE TITLE
Data Grid Not Show Filters

### ISSUE THREAD

**Issue by chuongmep** [macgile/DataGridFilter#22]
I don't know where this problem comes from, but in some of my projects sometimes they don't appear the filter, any suggestions for me to fix this, any answer is appreciated.
![image](https://user-images.githubusercontent.com/31106432/129853934-580835b3-4348-4d8e-8ccf-4aa25db33c86.png)

**Comment by macgile** [comment]
Can you clarify because, I do not understand the problem.

**Comment by chuongmep** [comment]
Means I use your sample project run with a few projects, some work normally, but one of them doesn't appear the filter on the title, which makes me quite confused and don't understand the reason why

**Comment by macgile** [comment]
you mean some fields in your collection don't appear in column headers?

**Comment by chuongmep** [comment]
I mean these select buttons, I've filled in the fields completely
![image](https://user-images.githubusercontent.com/31106432/129856044-cd1b19ba-d4b8-469b-a78b-800797be6301.png)
` <filterDataGrid:FilterDataGrid.Columns>
                            <filterDataGrid:DataGridTemplateColumn
                                Width="40"
                                FieldName="LastName"
                                Header="Checked"
                                IsColumnFiltered="True"
                                SortMemberPath="LastName">
                                <filterDataGrid:DataGridTemplateColumn.CellTemplate>
                                    <DataTemplate DataType="viewModel:ViewExtention">
                                        <CheckBox Click="DataCheckedClick" IsChecked="{Binding IsChecked, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
                                    </DataTemplate>
                                </filterDataGrid:DataGridTemplateColumn.CellTemplate>
                            </filterDataGrid:DataGridTemplateColumn>
                            <filterDataGrid:DataGridTemplateColumn
                                Width="Auto"
                                CanUserSort="True"
                                Header="Document"
                                FieldName="SheetViewID"
                                SortMemberPath="SheetViewID">
                                <DataGridTemplateColumn.HeaderStyle>
                                    <Style TargetType="{x:Type DataGridColumnHeader}">
                                        <Setter Property="HorizontalContentAlignment" Value="Center" />
                                    </Style>
                                </DataGridTemplateColumn.HeaderStyle>
                                <DataGridTemplateColumn.CellTemplate>

                                    <DataTemplate DataType="viewModel:ViewExtention">
                                        <TextBlock
                                            HorizontalAlignment="Left"
                                            Text="{Binding DocName, UpdateSourceTrigger=PropertyChanged}"
                                            TextAlignment="Left" />
                                    </DataTemplate>
                                </DataGridTemplateColumn.CellTemplate>
                            </filterDataGrid:DataGridTemplateColumn>

                            <filterDataGrid:DataGridTemplateColumn
                                FieldName="SheetViewID"
                                Header="View Id/Sheet Number"
                                IsColumnFiltered="True"
                                SortMemberPath="SheetViewID">
                                <filterDataGrid:DataGridTemplateColumn.CellTemplate>
                                    <DataTemplate DataType="viewModel:ViewExtention">
                                        <TextBlock Text="{Binding SheetViewID}" />
                                    </DataTemplate>
                                </filterDataGrid:DataGridTemplateColumn.CellTemplate>
                            </filterDataGrid:DataGridTemplateColumn>

                            <filterDataGrid:DataGridTextColumn
                                Binding="{Binding ViewName}"
                                Header="View/Sheet Name"
                                IsColumnFiltered="True" />

                            <filterDataGrid:DataGridTemplateColumn Width="*">
                                <DataGridTemplateColumn.HeaderStyle>
                                    <Style TargetType="{x:Type DataGridColumnHeader}">
                                        <Setter Property="HorizontalContentAlignment" Value="Center" />
                                    </Style>
                                </DataGridTemplateColumn.HeaderStyle>
                                <DataGridTemplateColumn.Header>
                                    <Grid>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="3*" />
                                            <ColumnDefinition Width="2*" />
                                        </Grid.ColumnDefinitions>
                                        <TextBlock Grid.Column="0" Text="Custom Sheet/View Name Export" />
                                        <Button
                                            x:Name="btnSetting"
                                            Grid.Column="1"
                                            Height="20"
                                            HorizontalAlignment="Right"
                                            VerticalAlignment="Center"
                                            Background="{x:Null}"
                                            BorderThickness="0"
                                            Click="BtnCustomName"
                                            Command="{Binding BtnSetting}"
                                            DockPanel.Dock="Right"
                                            ToolTip="Setting Custom Name Export">
                                            <Image Source="pack://application:,,,/OOG.Core;component/Resources/RevitUI_2181.ico" />
                                        </Button>
                                    </Grid>
                                </DataGridTemplateColumn.Header>
                                <DataGridTemplateColumn.CellTemplate>
                                    <DataTemplate DataType="viewModel:ViewExtention">
                                        <TextBlock
                                            HorizontalAlignment="Left"
                                            Text="{Binding CustomExportName, UpdateSourceTrigger=PropertyChanged}"
                                            TextAlignment="Left" />
                                    </DataTemplate>
                                </DataGridTemplateColumn.CellTemplate>
                            </filterDataGrid:DataGridTemplateColumn>

                        </filterDataGrid:FilterDataGrid.Columns>`

**Comment by chuongmep** [comment]
After I took them apart to test they work properly, So I want to investigate if the cause here is related to the exception events or not, because the tool I integrated is involved a lot custom controls.
![image](https://user-images.githubusercontent.com/31106432/129858096-949022a3-6dbb-462c-b5fd-434e24952c9d.png)

**Comment by chuongmep** [comment]
You can see problem
https://www.youtube.com/watch?v=WgBnTisW2Rg
A Project Demo In Develop Branch
https://github.com/chuongmep/RevitElementBipChecker/tree/develop
Image : 
![image](https://user-images.githubusercontent.com/31106432/129868975-a0e9131a-cbf0-4a52-8669-99f1f24b0cc9.png)

**Comment by chuongmep** [comment]
I still investigating this bug and found some related errors
![ảnh](https://user-images.githubusercontent.com/31106432/129998192-b106391d-9eef-42f0-b45f-fcaa7c08bbc5.png)

**Comment by macgile** [comment]
[FilterDataGrid.zip](https://github.com/macgile/DataGridFilter/files/7013329/FilterDataGrid.zip)
Try with this version, there is a problem with the sort function.
This is a temporary debug version

**Comment by chuongmep** [comment]
I has check , it hava issue with same problem prior.

**Comment by chuongmep** [comment]
https://user-images.githubusercontent.com/31106432/130046941-6a513419-a970-4c27-9e4b-a59c7d81480b.mp4

**Comment by chuongmep** [comment]
I have two file data csv and json sameple,hope can help you to reproduce the error.
[Report.csv](https://github.com/macgile/DataGridFilter/files/7013449/Report.csv)
[Report.json.zip](https://github.com/macgile/DataGridFilter/files/7013454/Report.json.zip)

**Comment by macgile** [comment]
I don't believe the problem is with the data, in my opinion it is with the binding of the "IsColumnFiltered" property as I understand it from the video.
To make the "IsColumnFiltered" property dynamic (with the checked box) you have to reload the collection so that the change is taken into account in the DataGrid if I understood correctly.

**Comment by macgile** [comment]
[FilterDataGrid.zip](https://github.com/macgile/DataGridFilter/files/7020855/FilterDataGrid.zip)
Here is a version which fixes the problem.
It is a debug version, confirmed to me if it is ok, so that I can put it in release version.

**Comment by chuongmep** [comment]
> [FilterDataGrid.zip](https://github.com/macgile/DataGridFilter/files/7020855/FilterDataGrid.zip)
> Here is a version which fixes the problem.
> It is a debug version, confirmed to me if it is ok, so that I can put it in release version.

Same Problem, it still not work when im open form.
