### ISSUE TITLE
[Question] Extending Filter Options

### ISSUE THREAD

**Issue by dyoung0224** [macgile/DataGridFilter#24]
Hello,

I'm new to C# and currently working on a learning project that essentially combines CSV log files from different sources and days into one unified view. I parsed each CSV file into a global List and attached it to a DataGridView object. This worked well, but I quickly realized that there are no "built-in" filtering functions that don't require a lot of knowledge and setup!

I needed a user-friendly UI to allow intuitive filtering "out of the box" for basic column types like int, datetime, and string. Your library is perfect! It looks and behaves almost exactly like Excel and couldn't be easier to implement. I've studied your code which has been helpful, although the scope is large and it is hard for me to understand sometimes.

Because I am combining log files, it is very common that a user might need to create more complex filters. For example, instead of text matching for an integer column, a user might need to filter using operators (<, >, =, !=, etc). Similarly for string, I want to implement "does not contain", "starts with", "ends with", etc and for DateTime I need a "Before date", "After date", etc.

Therefore I want to extend your project to add these additional filter operators. You have already written all the groundwork and "hard parts" so I feel like this would be a good project for me to continue expanding my C# experience. But I don't know where to start!

Do you have any suggestions on where I should start to begin expanding your FilterItem class to accommodate filter operators like <, >, !=, etc.? Or any tips/suggestions? Thank you!

**Comment by macgile** [comment]
This may be difficult for you, however it is possible to modify the behavior of the filters by extending the pop-up so that the user can choose the operators as in Excel. Then according to these choices, modify the filter if necessary. A good introduction to understanding how my code works is to read the article I wrote for the codeproject site.
https://www.codeproject.com/Articles/5292782/WPF-DataGrid-Filterable-multi-language
