### ISSUE TITLE
Filters stop working after source collection changes

### ISSUE THREAD

**Issue by JonatanKS** [macgile/DataGridFilter#25]
After the source collection changes the filters become unclickable, this can be seen if you try searching for a name and then try to click on a filter.

However, this seems not to happen if you use a filter before searching/updating collection.

![Screenshot_232](https://user-images.githubusercontent.com/7873920/131880138-8754d8c7-7194-4744-8282-f733f9de1def.png)

**Comment by macgile** [comment]
Hi,
This is fixed in the last commit, while waiting for me to update the NuGget package you have to compile the code by yourself, sorry for this inconvenience.

**Comment by JonatanKS** [comment]
Thank you very much, this works perfectly now.

**Comment by easyboot** [comment]
when Release the next version
