### ISSUE TITLE
How it works DateFormatString?

### ISSUE THREAD

**Issue by BEDIRHANSAMSA** [macgile/DataGridFilter#26]
How can i use DateFormatString? I tried dd-MM-yy hh:mm:ss but not worked.

**Comment by macgile** [comment]
Hi,

Try 
DateFormatString="dd-MM-yy hh:mm:ss"

![Capture](https://user-images.githubusercontent.com/577257/132954336-4ab36197-ff44-40dc-9053-3c23c0476451.PNG)

**Comment by BEDIRHANSAMSA** [comment]
I tried on a demo project it's working but in my project not working :/
![image](https://user-images.githubusercontent.com/44173331/132979800-667209cb-7166-4bac-b558-6be03a9f099e.png)

**Comment by macgile** [comment]
This problem is caused by the type you are not using from the FilterDataGrid.

**Comment by BEDIRHANSAMSA** [comment]
it looks like this

![image](https://user-images.githubusercontent.com/44173331/132995609-60363a78-e079-4754-9ef0-777c10e86e84.png)

**Comment by BEDIRHANSAMSA** [comment]
I found bug because of DateTimeOffset.

**Comment by BEDIRHANSAMSA** [comment]
And I fixed it in my fork you can look 
https://github.com/Akilli-Satici/DataGridFilter/commit/f7fa38f5573332d0bdc6e11904eb6edf847ddeda

**Comment by macgile** [comment]
> And I fixed it in my fork you can look
> [Akilli-Satici@f7fa38f](https://github.com/Akilli-Satici/DataGridFilter/commit/f7fa38f5573332d0bdc6e11904eb6edf847ddeda)

Indeed for the dates, I did not take into account the DateTimeOffset type, I will correct it.

Regards
