### ISSUE TITLE
DateTime Filtering is not Working

### ISSUE THREAD

**Issue by mpxxl** [macgile/DataGridFilter#28]
Version 1.2.3 (1.2.4 is not available on Nuget yet)

![image](https://user-images.githubusercontent.com/91209286/134374659-0d6e546d-c76c-4389-99e8-43ef49d515df.png)
![image](https://user-images.githubusercontent.com/91209286/134374684-f7990ff5-2481-41de-b5dc-d1139faf59a8.png)
![image](https://user-images.githubusercontent.com/91209286/134374733-3d657c27-8ae4-465f-b958-8a3ce2669780.png)
![image](https://user-images.githubusercontent.com/91209286/134374759-581ad850-ec25-4d16-b76b-4b4713f8fd2c.png)
![image](https://user-images.githubusercontent.com/91209286/134375490-3f93086c-52d7-4ee5-b6f9-dddf0fa923a9.png)

**Comment by macgile** [comment]
Yes it's strange, can you provide a sample of the data?

**Comment by mpxxl** [comment]
Sure:
[TestApp.zip](https://github.com/macgile/DataGridFilter/files/7216089/TestApp.zip)

**Comment by macgile** [comment]
Ok it's a bug, I'm going to commit a new version that fixes it.
In the meantime you can use this corrected version : 
[FilterDataGrid.zip](https://github.com/macgile/DataGridFilter/files/7217601/FilterDataGrid.zip)

**Comment by mpxxl** [comment]
Thank you!

**Comment by macgile** [comment]
Sorry this is the good version : 
[FilterDataGrid.zip](https://github.com/macgile/DataGridFilter/files/7217682/FilterDataGrid.zip)
