### ISSUE TITLE
Filter Icon/Dropdown not showing for Custom Columns

### ISSUE THREAD

**Issue by emptyindex** [macgile/DataGridFilter#34]
I have the NuGet package (v. 1.2.3) in my .NET 5.0 WPF Application and the filter icons do not appear when I try to create custom columns. Initially, I thought it was a problem with my data or my project so I created a clean project. I followed the demo project for .NET 5, stripping anything that wasn't completely necessary. However, the problem persists. Interestingly, the filter icons do appear when the columns are autogenerated. I included a zip of my clean project that shows the problem. Might be related to issue 22 (https://github.com/macgile/DataGridFilter/issues/22) but I tried using the Zip folder fix suggested and the problem persisted. Please let me know of any workarounds or suggestions. 
[ToDelete.zip](https://github.com/macgile/DataGridFilter/files/7549207/ToDelete.zip) 
![image](https://user-images.githubusercontent.com/48191269/142057934-e7b9571a-44de-42e1-804e-0f6f5da6b260.png)

**Comment by emptyindex** [comment]
To provide more context: I've tried this with the NuGet, the DLL, and by referencing the csproj directly but the icons still don't show on custom columns.

**Comment by emptyindex** [comment]
Update: it worked when I added a new project to the source code sln and copy/pasted the xaml directly from the Demo5 into the new project. However, it doesn't work if I copy the new project xaml into another project. Stepping through the code, the Columns property on the GridView itself was returning empty so the header style was not being applied (unless I copy/pasted exactly the Demo5 xaml code). This application is gaslighting me.

**Comment by SiberaIndustries** [comment]
I've got the exact same error. The Demo application works properly but the FilterDataGrid wont work in my own project

**Comment by macgile** [comment]
Yes, I could see this anomaly with the To Delete.zip project.
I will investigate to propose a fix.

**Comment by macgile** [comment]
In "MainWindow.cs" of the "ToDelete" project, change:
             this.DataContext = new ViewModel ();
             InitializeComponent ();

By
             InitializeComponent ();
             this.DataContext = new ViewModel ();

**Comment by macgile** [comment]
In "MainWindow.cs" of the "ToDelete" project, change:
             this.DataContext = new ViewModel ();
             InitializeComponent ();

By
             InitializeComponent ();
             this.DataContext = new ViewModel ();

Collections must be different instances (see ViewModel.cs file)

![Capture](https://user-images.githubusercontent.com/577257/142849449-7ce219f2-a8ac-497c-b7e1-51fe3d3f5da8.png)


To suppress the warning, change the 'TargetFramework' of the project file :
`<TargetFramework>net46-windows</TargetFramework>`

[ToDelete.zip](https://github.com/macgile/DataGridFilter/files/7582641/ToDelete.zip)
