### ISSUE TITLE
DateTime needs to be controlled for... or else popup for DateTime column seems weird.

### ISSUE THREAD

**Issue by insightllcio** [macgile/DataGridFilter#35]
Hello!

When working with this control I found that the popup/treeview on a DateTime column was seemingly reproducing days and wasn't filtering appropriately. 

I was able to resolve this by narrowing the value of my DateTime property to => prop.Date;

My DateTimes were complete date and times, and leaving the time portion of the value caused the Distinct call here
`// thank's Stefan Heimel for this contribution`
`UiDispatcher.Invoke(() =>`
`{`
`  sourceObjectList = Items.Cast<object>()`
`                                .Select(x => x.GetType().GetProperty(fieldName)?.GetValue(x, null))`
`                                .Distinct() // clear duplicate values first`
`                                .Select(item => item)`
`                                .ToList();`
`});`

to not clear the values as expected (because the times were different).  This wouldn't be an issue if the filter column was intended to also filter the times of the day, but that's not what it is intended for (and it makes sense to not do that).

**Comment by macgile** [comment]
Yes I am aware that the date filter does not take into account the hours because it would have been much more complex to implement, if not impossible because, how to filter on identical dates with different times, it is impossible.
I need to let other developers know that they need to exclude times from DateTime and DateTimeOffset fields.

**Comment by insightllcio** [comment]
Hi macgile, 

Here is a solution that may work in general. I won't pretend to fully understand the details of what you have done yet; I am very impressed with this work.

```
UiDispatcher.Invoke(() =>
  {
      sourceObjectList = Items.Cast<object>()
          .Select(x => x.GetType().GetProperty(fieldName)?.GetValue(x, null))
          .Select(item => (item is DateTime dtItem) ? dtItem.Date : item) //check for datetime and narrow
          .Distinct() // clear duplicate values 
          .ToList();
  });
```
