### ISSUE TITLE
Modification of the Popup style

### ISSUE THREAD

**Issue by Kruemelino** [macgile/DataGridFilter#38]
Hi,

First of all: Thank you for your application.

I am currently creating a dark mode for my application. How can I change the colors of the backgrounds, borders and icons of the popup? If I see it correctly, the colors are hard-coded in the [FilterDataGrid.xaml](https://github.com/macgile/DataGridFilter/blob/d76f2566df69c4caf91b6148664fd6cd948ab01e/Shared/Themes/FilterDataGrid.xaml). Is it possible to overwrite these values, or can you make an adjustment in your application?

e. g.
https://github.com/macgile/DataGridFilter/blob/d76f2566df69c4caf91b6148664fd6cd948ab01e/Shared/Themes/FilterDataGrid.xaml#L482-L483

Thank you

![image](https://user-images.githubusercontent.com/4273483/147730936-bf0c9763-6bda-40dd-b53a-eed36b75f8e5.png)

**Comment by macgile** [comment]
yes you can overwrite the values to customize the colors.
I will try later to make available to developers the possibility of using customizable themes.

**Comment by macgile** [comment]
on the other hand, if you change anything in FilterDataGrid.xaml, you must compile by yourself.

**Comment by Kruemelino** [comment]
I am aware of this and would like to avoid it. Therefore I am waiting for your modification.

**Comment by macgile** [comment]
Hi,
I really like the colors, can you provide me with the color palette used for the theme ?

**Comment by Kruemelino** [comment]
Hi,

This is my WPF theme library: https://github.com/Kruemelino/EasyWPFThemeLib
The color palette is taken from [Telerik: VisualStudio2013 Theme](https://docs.telerik.com/devtools/wpf/styling-and-appearance/themes-suite/visualstudio2013)

**Comment by Kruemelino** [comment]
I updated my solution. I have modified some BorderColors and BorderThickness as well as color definitions in such a way that they uses the colors of the selected design.

https://gist.github.com/Kruemelino/d49c6c57751556ab92b0938ecbac4f2e

**Comment by macgile** [comment]
I used your edits, hope it's good for you.
I didn't use EasyWPFThemeLib because I want FilterDataGrid to remain without any external dependencies.

best regards

**Comment by Kruemelino** [comment]
Hello,

Thank you for your changes. Unfortunately, two changes are still necessary:
You need to set the background color of the ListBox and TreeView to transparent. Otherwise, these two controls are displayed with a white background color.

https://github.com/macgile/DataGridFilter/blob/8c98b476ab7860889dab0b5f1365267922f15cb0/Shared/Themes/FilterDataGrid.xaml#L629

https://github.com/macgile/DataGridFilter/blob/8c98b476ab7860889dab0b5f1365267922f15cb0/Shared/Themes/FilterDataGrid.xaml#L687

**Comment by macgile** [comment]
I would modify this week when implementing the button to remove all filters at once !

best regards

**Comment by Kruemelino** [comment]
It's not intentional. It worked and I didn't think twice about it. Of course, if it works, you can refer to the ForeColor of the DataGrid as well.

**Comment by Kruemelino** [comment]
It looks good. I just have to define a separate style and define the colors separately. But that's ok.

I noticed one other thing. The German translation for the CheckBoxColumn is not correct. In German, one would say "ausgewählt" (selected) and "nicht ausgewählt" (not selected). It also depends on the context.

https://github.com/macgile/DataGridFilter/blob/e017f7b0b97922eca622e1abde47c42b4623cc77/Shared/Loc.cs#L207
and
https://github.com/macgile/DataGridFilter/blob/e017f7b0b97922eca622e1abde47c42b4623cc77/Shared/Loc.cs#L221
