### ISSUE TITLE
Keystrokes disgarded in popup search field

### ISSUE THREAD

**Issue by akraa** [macgile/DataGridFilter#39]
Using latest version 1.2.5

The filtering is working, however, I am not able to type into the search field of the popup. Pasting in a value works. Backspace works on a pasted string. And the space-bar works. But I am unable to enter any other input. ![image](https://user-images.githubusercontent.com/20170212/148566849-0cdf0199-fcf3-4cf7-b074-8a81efbbd011.png)

It seams to me that my key presses are being discarded for some reason. I don't have any key stoke handling in my part of the code so I don't know where this is happening.

Looking for any help I can get and thanks in advance.

**Comment by akraa** [comment]
Discovered  by accident that this issue was because of the way I was hosting a WPF window in Windows Forms. So no problems here.

**Comment by macgile** [comment]
Is everything working for you?
