### ISSUE TITLE
Suggestion: improve excel-like behaviour

### ISSUE THREAD

**Issue by wordiboi** [macgile/DataGridFilter#42]
Hi,

thanks for this great project, it's exactly what I've been looking for. However there are two things that refrain me from using the nuget package as it is.

- When you open the popup by clicking the button and then clicking the button again, you accidently reorder the button's column instead of just closing the popup. In excel this would simply close the popup.

- When you click somewhere on the popups background (which is not a button, checkbox or text) it will automatically close the popup and probably cause some unwanted "clickthrough" effect depending on where you click. Also the "main" window is still active while popup is open, so any click inside the datagrid, the buttons or whatever might cause unwanted behaviour when you just want to close the popup by clicking anywhere outside the popup.

Therefore I added these few lines of code:

in ShowFilterCommand() I added:

```
// disable popup background clickthrough
popup.MouseDown += (s, eArgs) => eArgs.Handled = true;
// disable datagrid while popup is open
var parent = VisualTreeHelpers.FindAncestor<FilterDataGrid>(popup);
parent.IsEnabled = false;
```

as the comment says this disables the popup from closing when clicking on the popup background, it also disabled any click events to the main window in the background (e.g. datagrid) while the popup is open.

in void PopupClosed() I'm just reenabling the window again:

```
var parent = VisualTreeHelpers.FindAncestor<FilterDataGrid>(pop);
parent.IsEnabled = true;
```

In my opinion these changes make it a bit more intuitive as it behaves a little bit more like Excel itself.

**Comment by macgile** [comment]
Thank you, any suggestions for improvement are welcome.

**Comment by ottosson** [comment]
I'd just like to add (as I mentioned in my now closed duplicate issues) that clickthrough also happens when clicking disabled components.

**Comment by macgile** [comment]
This improvement was included in the last commit.
Thank you for your participation
Best regards
