### ISSUE TITLE
Q: How can I programatically add columns with filter?

### ISSUE THREAD

**Issue by ottosson** [macgile/DataGridFilter#43]
Hi! This project is great! Thanks a lot!

I have a question though. I'm using DataGridFilter in conjunction with BindableColumns from [this post on StackOverflow ](https://stackoverflow.com/a/4379965/1644471) to be able to add columns dynamically when utilizing MVVM. This means I'm adding columns programaticaly (in the ViewModel) like this:

```
public ObservableCollection<DataGridColumn> Columns { get; set; }
...
Columns.Add(new FilterDataGrid.DataGridTextColumn()
{
    Header = "Name",
    IsColumnFiltered = true,
    Binding = new Binding() {...},
    HeaderTemplate = ???,
});
```
I guess I have to fetch the HeaderTemplate, but is that possible from a viewmodel? Can I add a reference to the DataGridHeaderTemplate resource in my application resources somehow maybe?

Thanks!

**Comment by macgile** [comment]
As I understand this solution can't work with FilterDataGrid because FilterDataGrid relies on "ItemSource" property, filterable fields are built from source collection not from source collection of type "DataGridColumn.

**Comment by ottosson** [comment]
Hmm... that's unfortunate. Do you think it would be doable to fork DataGridFilter and add BindableColumns myself?

If not: Would you know of any other way to add columns dynamically from a viewmodel?

**Comment by macgile** [comment]
As it is the collection (and the fields that compose it) that determine the columns of the **datagrid** via the **ItemsSource** property, it is the source collection that must be changed, the problem is that this will only work for generated columns automatically.

**Comment by ottosson** [comment]
Would it be a viable solution to add logic to OnItemsSourceChanged to update the columns at the same time as the ItemSource changes?

https://github.com/macgile/DataGridFilter/blob/c7c02b2c6b0bbf60e4c09e6666c39a25c3482f16/Shared/FilterDataGrid.cs#L371 

Much like GeneratingCustomsColumn does today but based on the content of the ItemSource?
https://github.com/macgile/DataGridFilter/blob/c7c02b2c6b0bbf60e4c09e6666c39a25c3482f16/Shared/FilterDataGrid.cs#L411

**Comment by ottosson** [comment]
hmm, that's true. I'll have to think about this. There must be a way. I'm surely not the first person to have this need...
