### ISSUE TITLE
Very slow select all cells after opening filter popup

### ISSUE THREAD

**Issue by ottosson** [macgile/DataGridFilter#44]
When I select all table cells using the top-left gutter button it works just fine. But after I've opened any filter popup once selecting all cells hangs the application (even if I open a filter popup on the second table of the demo application):

![datagridfilter_hang](https://user-images.githubusercontent.com/3355320/154687093-15895eba-5c64-4495-a956-c601d8454325.gif)

Edit: It doesn't hang, it just gets incredibly slow to select/deselect all cells.

**Comment by macgile** [comment]
It's a datagrid problem, not the filter.
I haven't found a solution for this, even using the virtualization panel.
The datagrid thaws after a while, I agree this is not acceptable behavior.

**Comment by ottosson** [comment]
That's a shame... I found this when looking around a bit: https://github.com/dotnet/wpf/discussions/5588#discussioncomment-1552173. Just FYI.
