### ISSUE TITLE
Clicking popup background clicks through popup

### ISSUE THREAD

**Issue by ottosson** [macgile/DataGridFilter#46]
When I click on the background of the popup I get hold of the column header that lines up with the mouse cursor. Same anywhere on the popup that is not a control, unless if it's a disabled controls (like the ok button before anything is changed), then it behaves the same as if I click the background.

![datagridfilter_click_background](https://user-images.githubusercontent.com/3355320/154714735-493771fe-8dc3-4573-af3e-8ccb46a5173f.gif)

**Comment by ottosson** [comment]
Very nice to hear. I think this is the best open source "datagrid with filter" component that I've seen so far. I wish I could be of help, but I have to get more familiar with the code base as well as the fundamentals of the WPF datagrid component.

Do you know of any good resource to get more familiar with the DataGrid component? I think I've seen the source code for it somewhere, but can't find it anymore...

**Comment by macgile** [comment]
Thanks for the link, any improvement suggestions are welcome.

**Comment by ottosson** [comment]
I just realized I committed the first sin of posting issues as I didn't check existing posts before.
There is https://github.com/macgile/DataGridFilter/issues/42 that points out my findings as well....
