### ISSUE TITLE
Unknown build error, 'An item with the same key has already been added.'

### ISSUE THREAD

**Issue by Ja7373** [macgile/DataGridFilter#47]
Sometimes when generating the project I get this error
**Unknown build error**, 'An item with the same key has already been added.'

This happens in **DemoApplication** or in **DemoApp.Net5.0** 
if I Clean and Rebuild the solution and change the startup project it stops this error.
Do you know what this error is?

Thanks

**Comment by macgile** [comment]
These errors will be fixed with the next commit.
The next commit comes for the end of this week or next week.

**Comment by Ja7373** [comment]
Thanks 
It's a great job.
