### ISSUE TITLE
Crash when applying filter while in edit mode: ''Refresh' is not allowed during an AddNew or EditItem transaction.'

### ISSUE THREAD

**Issue by ottosson** [macgile/DataGridFilter#48]
Repro in sample application:
1. set grid to IsReadOnly="False" to be able to edit cells
2. start application
3. start editing cell
4. apply new filter while in edit mode
7. crash!

![datagridfilter_crash](https://user-images.githubusercontent.com/3355320/156572849-cbdc865e-6d01-4d49-a272-e0d37e27065e.gif)

Maybe the grid could cancel the current transaction before it applies the filter or perhaps when opening the filter dialog?

**Comment by ottosson** [comment]
I don't know if this is the best solution, but at the start of ShowFilterCommand I added CommitEdit(DataGridEditingUnit.Row, true); which seems to resolve the issue.

**Comment by macgile** [comment]
Added to last commit, at the moment this feature is untested, I don't know if it can cause unexpected effects !
Best regards

**Comment by ottosson** [comment]
I found this way to do the same: https://github.com/dotnet/DataGridExtensions/blob/master/src/DataGridExtensions/Tools.cs#L171

Just add two CommitEdit() instead of CommitEdit(DataGridEditingUnit.Row, true); I don't know... Maybe it's the same in the end.

But that's a repo under the .net foundation which might indicate some sort of quality. =)
