### ISSUE TITLE
Feature request: Select all column cells when clicking header

### ISSUE THREAD

**Issue by ottosson** [macgile/DataGridFilter#49]
Clicking the column header will trigger a sort of the column which means it's quite difficult to select all cells in the column unless you know the keyboard commands.

Would it be appropriate to change the behavior to select the cells for the column if clicking the white space around the text, and sorting when clicking the text in the column header? Also tri-state sorting would be nice (ascending, descending and no sorting)? I'm used to work with Handsontable (https://handsontable.com/demo) and think they have a couple of good ideas implemented in their grid.

**Comment by macgile** [comment]
My intention is not to make a "super datagrid" but just to offer developers the possibility to implement without too much effort a datagrid control with filterable columns.

**Comment by ottosson** [comment]
I get it. One can only dream! ;) Thanks anyway.
