### ISSUE TITLE
User defined ColumnWidth not possible

### ISSUE THREAD

**Issue by Apflkuacha** [macgile/DataGridFilter#5]
The column width could only be *, it is set by `<Setter Property="ColumnWidth" Value="*" />` in the File FilterDataGrid.xaml.
I wish that the columns could have a user defined width or Auto instead of *

When setting it to Auto or removing the line mentioned above the FilterDataGrid gets laggy - could be easily tested with removing that line in the DemoApplication

**Comment by macgile** [comment]
I fixed this today :)
