### ISSUE TITLE
Showing multiple times the same day

### ISSUE THREAD

**Issue by mgaszynski** [macgile/DataGridFilter#54]
When I use dates with time in a column, I get repeating days and filtering doesn't work:

![image](https://user-images.githubusercontent.com/100915697/158760799-8f80ecdd-073e-4d16-9464-c81086b353ee.png)
![image](https://user-images.githubusercontent.com/100915697/158763194-05066f65-68ba-4f08-b887-31a92f8b425c.png)

My suggestion is to change method _BuildTree_ in _FilterCommon.cs_ file from:

```
foreach (var y in from date in dateTimes.Where(d => d != null)
                        .Select(d => (DateTime)d).OrderBy(o => o.Year)
```

to:

```
foreach (var y in from date in dateTimes.Where(d => d != null)
                        .Select(d => ((DateTime)d).Date).Distinct().OrderBy(o => o.Year)
```

And then in method _AddFilter_ change from:

```
var value = o.GetType().GetProperty(FieldName)?.GetValue(o, null);
return !PreviouslyFilteredItems.Contains(value);
```

to:

```
var value = o.GetType().GetProperty(FieldName)?.GetValue(o, null);
var dateTimeParse = DateTime.TryParse(value.ToString(), out DateTime dateTime);
 if (dateTimeParse)
     return !PreviouslyFilteredItems.Contains(dateTime.Date);
return !PreviouslyFilteredItems.Contains(value);
```

**Comment by macgile** [comment]
Fixed in version 1.2.5.2

best regards
