### ISSUE TITLE
Feature request: Combobox and checkbox column.

### ISSUE THREAD

**Issue by livep2000** [macgile/DataGridFilter#55]
What an amazing tool ! Thanks for this.

I'm working on a inventory tool, make filtering look-n-feel like this will make it more convenient  for my users to learn using it.

It works out of the box with DBContext, .NET 6.0,  Entity Framework Core 6.0 and related data.

I needed the "DataGridComboBoxColumn" to filter on, so tried to implement the "DataGridTemplateColumn" with custom combo, I'm sure that must be possible, but with my lack of knowledge I came to filtering the indexes instead of the values. 

![Capture](https://user-images.githubusercontent.com/2779309/159202200-0cd819a7-6c4f-460b-add9-d0ab6106aae5.PNG)

So, tried another approach and tried to patch your code, how nice would it be if the DataGridComboBoxColumn and DataGridCheckBoxColumn are in there and acting exact as the standard control.

Again, my lack of of knowledge brought me until filtering the indexes, hacking into your filtering code is way above my head.

Thanks for reading.

**Comment by livep2000** [comment]
I'm closing this request. 
I share the combobox and checkbox column in a fork :

[https://github.com/livep2000/DataGridFilter](https://github.com/livep2000/DataGridFilter)

Please take a look and evaluate if it is worth using.

**Comment by macgile** [comment]
I look at your code and give you feedback if it seems interesting to me to include it in the next version.

best regards

**Comment by macgile** [comment]
I added DataGridCheckBoxColumn according to your code.

best regards

**Comment by RejeanLabbe** [comment]
@macgile Are you planning to add DataGridCombobox in a next future?

**Comment by elvisw** [comment]
Is DataGridCheckBoxColumn available now
