### ISSUE TITLE
Display the number of groups after filtering function

### ISSUE THREAD

**Issue by easyboot** [macgile/DataGridFilter#56]
Display the number of groups after filtering function

**Comment by macgile** [comment]
Please be more explicit !

best regards

**Comment by easyboot** [comment]
![image](https://user-images.githubusercontent.com/26960023/163658748-c5f9683a-c31d-42e5-92f0-438711beeb38.png)
i want to know the filter record count,

**Comment by easyboot** [comment]
> 
I want to know the quantity of filtered data, such as the total quantity of 4701
