### ISSUE TITLE
Feature request: Time Column Filter

### ISSUE THREAD

**Issue by TanQianTing** [macgile/DataGridFilter#57]

**Comment by macgile** [comment]
Please be more explicit !

**Comment by TanQianTing** [comment]
Hi, 
I would like to customize the time filter column with custom groupings and time intervals.

For example:

- group 1
    - 00:00 - 01:00 (time range 1)
         - 00:00
         - ...
         - 00:59
   - 01:00 - 02:00  (time range 2)
   - ...
- group 2
    - 05:00 - 06:00
    - ...

Is there a way that I can achieve this grouping? I imagine it to be something similar to the grouping of dates into months of the Date column.

**Comment by macgile** [comment]
It is possible to do it but you will have to do it yourself because it is a specific request for a specific development.

**Comment by APerricone** [comment]
> It is possible to do it but you will have to do it yourself because it is a specific request for a specific development.

Can you give us some hint about how do it? I read the CodeProject article and the look the code but I don't see how to hang for a custom flter...
