### ISSUE TITLE
I can‘t use FilterDataGrid 1.2.5.2 

### ISSUE THREAD

**Issue by easyboot** [macgile/DataGridFilter#59]
![image](https://user-images.githubusercontent.com/26960023/164585272-92c1c286-7984-4c86-8fa3-c8a4a9cd0dcf.png)

my project use FilterDatagrid 1.2.3.0 in .net core 3.1 ,it work;
but i use 1.2.5.2 don't work 
how can I do?

**Comment by macgile** [comment]
use the latest version of this repository, the different versions of .NET are better supported.
