### ISSUE TITLE
Horizontal Offset in Popup Filter Window for Columns.DisplayIndex > 0 is not accurate

### ISSUE THREAD

**Issue by chocominyo** [macgile/DataGridFilter#6]
There are certain scenarios where the popup window is displaced out the main application due to an invalid offset number.

This can be corrected if we keep the offset value static.
**Instead of using this code:**
https://github.com/macgile/DataGridFilter/blob/d726a5f3023e80d364cffbf0f29d2fe5cfb94a54/FilterDataGrid/FilterDataGrid.cs#L1156

**Change it to:**
popup.HorizontalOffset = 1d;

**Comment by macgile** [comment]
Hi,
Thank you for your remark, I am correcting the positioning of the popup so that it does not overflow the window when resizing.
I'll push an update when it's good.

Regards

**Comment by chocominyo** [comment]
> Hi,
> Thank you for your remark, I am correcting the positioning of the po-pup so that it does not overflow when resizing, especially in floating windows.
> I'll do an update when it's okay
> 
> Regards

That's fantastic! And thanks a lot for building this control, it works really well! Good job.

**Comment by macgile** [comment]
Hi,
I corrected, I think it's good.

Regards
