### ISSUE TITLE
When I press the button filter the program stop working

### ISSUE THREAD

**Issue by juandgilygil** [macgile/DataGridFilter#63]
![image](https://user-images.githubusercontent.com/98051995/169109544-504e999e-1e5c-4b3d-a3ca-f4b0bd264655.png)

Look, let me translate it to you...
It said: " { -333.5066... } is not a valid value for the property 'MaxWidth' ".

**Comment by macgile** [comment]
this is fixed in the current version of the repository.

best regards

**Comment by juandgilygil** [comment]
I will check that. Greetings from Mexico. You guys are making and incredible work.
