### ISSUE TITLE
Spanish lenguage

### ISSUE THREAD

**Issue by juandgilygil** [macgile/DataGridFilter#64]
Hi DataGridFilter collaborators, I'm here again just for send you a little help with the spanish lenguage to the Loc.cs

**Local enum:**
`Spanish`

**CultureNames:**
`{ Local.Spanish, "es-ES" }`

**All:**
`{ Local.Spanish, "(Seleccionar todos)" }`

**Empty:**
`{ Local.Spanish, "(Vacio)"}`

**Clear:**
`{ Local.Spanish, "Limpiar filtros \"{0}\"" }`

**Contains:**
`{ Local.Spanish, "Buscar (contiene)" }`

**StartsWith:**
`{ Local.Spanish, "Buscar (comienza con)" }`

**Toggle:**
`{ Local.Spanish, "Toggle contiene/comienza con" }`

**Ok:**
`{ Local.Spanish, "Aceptar" }`

**Cancel:**
`{ Local.Spanish, "Cancelar" }`

**Status:**
`{ Local.Spanish, "{0:n0} registro(s) encontrado(s) de {1:n0}"}`

**ElapsedTime:**
`{ Local.Spanish, "Tiempo transurrido {0:mm}:{0:ss}.{0:ff}"}`

**Comment by macgile** [comment]
Hi,
Added Spanish language !
thank's

best regards
