### ISSUE TITLE
Incorrect result when filtering across multiple columns

### ISSUE THREAD

**Issue by Patrick-Echterhoff** [macgile/DataGridFilter#65]
Hello,

if you set a filter on the column First Name and then set another filter on the column Last Name and then clear the filter on the column First Name , the result of the filter on the column Last Name  is no longer correct, even the selection of filters on the column Last name is no longer correct.

Then I would have the suggestion to be able to show and hide columns via a context menu by right-clicking in the column header.

Greetings Patrick

![First_name_filter_Alexander_Alex](https://user-images.githubusercontent.com/33514154/170887516-69165692-0f1a-4c03-9872-a1d21a47d9f3.jpg)

![Last_name_filter_Bairoxaqu_Baubygys_Beacicubi](https://user-images.githubusercontent.com/33514154/170887592-8070aaed-5c8f-4f68-bda6-c42602ea3d0a.jpg)

![After_clear_First_name_filter](https://user-images.githubusercontent.com/33514154/170887634-cd172ae4-b209-4b5e-8c06-3ffaf5b84b74.jpg)

![Incorrect_filter_Last_name](https://user-images.githubusercontent.com/33514154/170888028-610d7d1c-4a39-43e4-ab77-4e6aab6f34f3.jpg)

**Comment by macgile** [comment]
Please use the version from the "master-testing" branch, this works exactly like the excel filters.
In a future version it will be possible to choose between the two filtering methods.

best regards
