### ISSUE TITLE
Add a ClearFilters method

### ISSUE THREAD

**Issue by Foitn** [macgile/DataGridFilter#66]
So for one of my projects I'm using this lovely library and I need to add a button to the UI, with which I can clear all active filters from the  FilterDataGrid.

I would like for a method to be added called something like "ClearFilters", which will return the state of the FilterDataGrid to the one where no Filter is active at all.

**Comment by macgile** [comment]
I added the possibility to remove all filters using a button located in the upper right edge of the datagrid.

best regards

**Comment by Foitn** [comment]
@macgile Awesome, thanks!

**Comment by padovanl** [comment]
is there a method that i can call directly on the datagrid object?
