### ISSUE TITLE
Filter function does not work when binding is set to nested class property

### ISSUE THREAD

**Issue by Zefan-Wang** [macgile/DataGridFilter#69]
Hi, I am using FilterDataGrid version 1.2.5.

I have a FilterDataGrid , which itemsource is bound to an observable collection of class objects. These objects have a nested class property that will cause the filter function for that column to show up as blank.

Example:

Public Class Person
    Public Property Name As **PersonName**
    Public Property Race As String
    Public Property Religion As String
End Class

Public Class **PersonName**
    Public Property FirstName As String
    Public Property LastName As String
End Class

So then my FilterDataGrid's ItemSource will be bound to an ObservableCollection(Of Person), and the DataGridTextColumn will be bound to regular properties such as Race and Religion. 
All of this works fine, however, the issue arises the moment I change the binding for the DataGridTextClolumn to Binding = "{Binding Name.**LastName**}" or Binding = "{Binding Name.**FirstName**}" 
The column will still be correctly populated with the corresponding data, but the filter dropdown will show blank. 

Could you kindly advise on this issue? 
Thanks in advance.

**Comment by macgile** [comment]
The columns of the datagrid are constructed from the collection provided to the ItemsSource property, this is the normal operation of the datagrid, including that of FilterDataGrid.
So when the construction of the column headers happens to the "name" property of your "Person" class it is considered to be a simple property of type "unknown", it cannot "know" that it is a property of 'a class other than "Person"

**Comment by macgile** [comment]
The easiest is to use your second solution
