### ISSUE TITLE
The values of the items in the popup filter are not visible in DemoApp.Net5.0

### ISSUE THREAD

**Issue by ChM40** [macgile/DataGridFilter#70]
Try to use last commit [adding DataGridCheckBoxColumn](https://github.com/macgile/DataGridFilter/commit/53fc7664d7d8304f73772cd4d609686971c399a2)

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/50195717/173181171-c24b91da-d88e-4f33-9ce2-18eed983aabe.png">

Try in debug and release mode, got same result.

Thank's for your great work.

**Comment by macgile** [comment]
Ok j'ai corrigé

Merci de l'avoir signalé :)

**Comment by ChM40** [comment]
Fixed on  last commit
Merci
