### ISSUE TITLE
Setting the filter for a column from programmatically

### ISSUE THREAD

**Issue by anthonypark0907** [macgile/DataGridFilter#71]
Hi I just began using your filterdatagrid and I was wondering if there is a way to set the filter of a column programmatically from the backend.

For example: when button "a" is clicked, column 1 should be filtered for every row that has the value "apple" and when the button "b" is clicked, column 2 should be filtered for every row that has the value "bee".

**Comment by macgile** [comment]
There is no backend, but you can extend the FiterDatagrid class.

best regards

**Comment by RaceX58** [comment]
Hello,

Could you please post an example of how it would work?

I've tried it myself but with no luck...

Thanks in advance,

RaceX

**Comment by RejeanLabbe** [comment]
@macgile I'm also curious about that. It would be great to be able to set filter items source to a column by binding an observable collection.

Thanks
