### ISSUE TITLE
Nothing loading

### ISSUE THREAD

**Issue by mbaksh01** [macgile/DataGridFilter#74]
Hi All.

I was using the nuget package in .NET Framework 4.7.2 and it was working fine. I then migrated the project to .NET 6 and then the gird no longer appeared. I'm not sure if it is because I am using .NET 6 or if I am doing something wrong, but any help would be much appreciated.

My current code:
XAML:

```
xmlns:control="http://filterdatagrid.control.com/2021"
...
<control:FilterDataGrid x:Name="filterGrid" Grid.Column="1" Grid.Row="2" Grid.ColumnSpan="2"></control:FilterDataGrid>
```

XAML.CS:

```
...
filterGrid.DataContext = viewModel;
filterGrid.ItemsSource = viewModel.Contracts;
filterGrid.AutoGeneratedColumns += (_, _) =>
{
     filterGrid.Columns.RemoveAt(0);
     filterGrid.Columns.Move(10, 0);
     filterGrid.Columns.Move(13, 0);
     filterGrid.Columns[0].Header = "Contract (JobID)";
     filterGrid.Columns.RemoveAt(7);
     filterGrid.Columns.RemoveAt(13);
     filterGrid.Columns.RemoveAt(13);
     filterGrid.Columns.RemoveAt(13);
     filterGrid.Columns.RemoveAt(13);
};
```

Contracts is a ```IEnumerable<Contract>``` which is loaded before this code.

**Comment by easyboot** [comment]
I have the same problem. I use Net core 3.1, I use 1.2.5 is normal, when I upgrade to 1.2.6 is not displayed.

**Comment by mari-net** [comment]
I have the same problem. Version 1.2.5 works normally, after updating to 1.2.6 the grid does not appear. The project is .NET 6, Nuget package.

**Comment by mbaksh01** [comment]
So as long as I use version 1.2.5 everything should work as expected?

**Comment by macgile** [comment]
Several of you report this problem, do you all use the same method of loading data?

**Comment by mari-net** [comment]
> Several of you report this problem, do you use the same method of **mbaksh01** to load the data?

I have tried several variants, for example this one works fine in 1.2.5 but not in 1.2.6.

On my XAML: <control:FilterDataGrid x:Name="someFilterDataGrid" ShowStatusBar="True"></control:FilterDataGrid> also tried with AutoGenerateColumns="True"

Code behind:
someFilterDataGrid.ItemSource = System.Windows.Data.CollectionViewSource.GetDefaultView(... filled e.g. with List<string>....);
even .Refresh() didn't help

**Comment by macgile** [comment]
Hi All,
Specify :
- Version of your project (.NET Framework or .NET)
- NuGet package version
- The FilterDataGrid version of the NuGet package
- Visual Studio version
- Also indicate your way of feeding FilterDataGrid data

best regards

**Comment by mbaksh01** [comment]
Version of your project (.NET Framework or .NET) =>  .NET 6
NuGet package version => 3.5.0.1938
The FilterDataGrid version of the NuGet package => 1.2.6
Visual Studio version => VS 2022 17.3.3
Also indicate your way of feeding FilterDataGrid data => 

1. Set `ItemSource` to a `IEnumerable` list.
2. Set `IsReadOnly` to `true`.
3. Add `AutoGeneratedColumns` event handler to arrange columns in custom order.
4. Pass the `FilterDataGrid` to the `System.Windows.Controls.Frame` `Content` property to be displayed.

**Comment by mari-net** [comment]
Version of your project (.NET Framework or .NET) => .NET 6
NuGet package version => from nuget.org 1.2.6 published 6/15/2022
The FilterDataGrid version of the NuGet package => 1.2.6
Visual Studio version => 2022 17.3.3
Also indicate your way of feeding FilterDataGrid data => please see my comment from [Aug 9](https://github.com/macgile/DataGridFilter/issues/74#issuecomment-1209344255)

**Comment by macgile** [comment]
Hi all,

The problem with loading probably stems from where and when you feed the "items source" property of FilterDataGrid .
FilterDataGrid works the same way as a Datagrid.
If you don't implement INotifyPropertyChanged to notify that the "items source" property has been updated, use the "Loaded" event of FilterDataGrid to do further processing on the columns.
Here is an example :

// MainWindows.cs
List<User> items = new List<User>
{
    new() { Name = "John Doe", Mail = "test_1@mail.com", Age = 42, Sex = SexType.Male },
    new() { Name = "Jane Doe", Mail = "test_2@mail.com", Age = 39, Sex = SexType.Female },
    new() { Name = "Sammy Doe",Mail = "test_3@mail.com",  Age = 13, Sex = SexType.Male },
    new() { Name = "Donna Doe",Mail = "test_4@mail.com",  Age = 13, Sex = SexType.Female }
};

filterGrid.ItemsSource = items;

            filterGrid.Loaded += (_, _) =>
            {
                filterGrid.Columns.RemoveAt(3);
                filterGrid.Columns.Move(1, 0);
                filterGrid.Columns.Move(2, 1);
                filterGrid.Columns[0].Header = "Contract (JobID)";
            };

// test class
public enum SexType { Male, Female };

public class User
{
    public string Name { get; set; }

    public int Age { get; set; }

    public string Mail { get; set; }

    public SexType Sex { get; set; }
}

Please see the demo applications provided with the code of FilterDataGrid.

Best regards
