### ISSUE TITLE
Popup transparency

### ISSUE THREAD

**Issue by AdrienPointeau** [macgile/DataGridFilter#77]
Hello!

Is it possible to set the background transparency of the popup?
It appears in transparency and I'd like to deny it:

![GIF 11-10-2022 12-46-21](https://user-images.githubusercontent.com/82660377/195070460-d5a0e01d-f1f0-4cc4-b8aa-fd5532b7c456.gif)

Have a nice day!

**Comment by macgile** [comment]
The background color of the pop up inherits the background color of the host window, check if yours is not transparent!

best regard

**Comment by AdrienPointeau** [comment]
Thanks for your response !
But my host window needs to be transparent for other functionalities.
Is it possible to force just the non-transparency  of the popup?

Regards !

**Comment by macgile** [comment]
You can put AllowsTransparency="False" directly in the FilterDataGrid.xaml file and compile a version specifically for your use.

best regard
