### ISSUE TITLE
Is it possible to have Japanese added to Local?

### ISSUE THREAD

**Issue by iBadaMorae** [macgile/DataGridFilter#79]
I am developing in Japanese environment. 
FilterDataGrid has excellent filtering capabilities. 
Thank you very much for providing it for free. 
There is no Japanese in the display language, 
But is it possible to have Japanese added?

**Comment by macgile** [comment]
Yes it is possible, as Japanese is not my native language, please provide me with the translation using the Loc.cs file in the folder as a model: DataGridFilter/Shared/Loc.cs
I would integrate the Japanese according to your translation.

best regards

**Comment by iBadaMorae** [comment]
Thank you for your understanding.
I add Japanese to Loc.cs and request a commit.
best regards

**Comment by macgile** [comment]
Thank you for your participation
