### ISSUE TITLE
Fuzzy query

### ISSUE THREAD

**Issue by FreeVB** [macgile/DataGridFilter#8]
Can the "Global search" function realize fuzzy search? 
For example, if the Last Name is "Baabyp", entering "aby" can also display the result that contains "Baabyp".

**Comment by macgile** [comment]
Hi,
if you are talking about the global search of the demo application you can yourself change the filter of the modelview, replacing StartsWith with Contains.

Regards

**Comment by FreeVB** [comment]
Put the original
`return item != null && ((item.LastName?.StartsWith(search, StringComparison.OrdinalIgnoreCase) ?? false) || (item.FirstName?.StartsWith(search, StringComparison.OrdinalIgnoreCase) ?? false));`
change into
`return item != null && ((item.LastName?.Contains(search) ?? false) || (item.FirstName?.Contains(search) ?? false));`

Work well, thank you for your reply
