### ISSUE TITLE
Version 1.2.7 clicking filter does not open pop menu

### ISSUE THREAD

**Issue by VashBaldeus** [macgile/DataGridFilter#88]
Quite simple, downloaded the release source, compiled, added it to my project and I am encountering a situation where upon clicking the filter it shows the mouse thinking icon and nothing happens.

I am using MahApps and PostSharp, which should not cause an issue...
Placed DataGrid control in a UserControl window.

Current XAML:
```
        <filterDataGrid:FilterDataGrid x:Name="VehicleCatalog"
            ItemsSource="{Binding Catalog}"
            AutoGenerateColumns="False" IsReadOnly="True"
            DateFormatString="d" FilterLanguage="English" ShowStatusBar="True">
            <filterDataGrid:FilterDataGrid.Columns> 
                <filterDataGrid:DataGridTextColumn IsColumnFiltered="True" Width="*"
                                                   Header="Model" Binding="{Binding Vehicle_Name}"/>
            </filterDataGrid:FilterDataGrid.Columns>
        </filterDataGrid:FilterDataGrid>
```

I tried versions from Nuget:
- 1.2.6, does not display DataGrid at all.
- 1.2.5 throws error when clicking filter button saying `'-1000' is not a valid value for property 'MaxWidth'`.

**Comment by macgile** [comment]
Hi, 
I'm on vacation right now, I'll respond when I get back.
Best regards

**Comment by VashBaldeus** [comment]
I has been a week, is there an estimate of when you will be able to assist as I have noticed more than one issue piling up with similar issue as mine.

**Comment by macgile** [comment]
hi VashBaldeus,

I am working on this project for free and on my free time, please allow me to take a few vacations.

However, today I replied to your other posts and thank you for your contribution.

best regards
