### ISSUE TITLE
Reset all filters and filter in code-behind

### ISSUE THREAD

**Issue by NedSeby** [macgile/DataGridFilter#9]
Is there any way to reset all applied filters via button click event for a specific datagrid?
Also, I tried to figure out a way to add a filter for a specific column in code-behind for quick filter actions. Is this possible?

**Comment by macgile** [comment]
Hi,
The demo application already implements resetting the source collection via the reset button, you can get inspiration from it.
I don't understand the second question.
Regards

**Comment by NedSeby** [comment]
Hello,
Thanks for your answer.
Regarding to my second question. I want to create menu buttons for quick filters.
For example: When I press a button, my datagrid will be filtered automatically on column x where cell value equals "ALERT" without the need to apply the filter manually in that column.

**Comment by macgile** [comment]
If your intention is not to use the column filters you will find your answer on the net, there are many examples.
Regards
