### ISSUE TITLE
Grid does not display

### ISSUE THREAD

**Issue by mattcarlucci** [macgile/DataGridFilter#90]
Context: 

.Net 6 WPF Application, 

using both Syncfusion controls such as SfDataGrid 20.3.0.60 and built-in DataGrid. 

Looking to replace both with DataGridFilter, hopefully

After Installing FilterDataGrid 1.2.6 and making necessary changes , the FilterDataGrid does not show up. It's an empty rectangle. No Errors that I can see.  I've tried in many areas of my Wpf application and get the same result. 

Seems to only effect projects with Syncfusion installed. If I create a clean new project, it works fine.

![FilterDataGridSnapshot](https://user-images.githubusercontent.com/5778393/210615711-ff447694-9db1-41d0-b734-928ee59dc184.png)

Xaml:

  <g:FilterDataGrid
            Name="gridView"
            AlternatingRowBackground="WhiteSmoke"
            AutoGenerateColumns="False"
            ShowRowsCount="True"
            Visibility="Visible"
            DateFormatString="d"
            DockPanel.Dock="Bottom"
            FilterLanguage="English"
            Foreground="DarkBlue"
            HorizontalGridLinesBrush="LightGray"
            IsReadOnly="True"
            RowHeaderWidth="0"
            SelectionMode="Extended"
            ShowElapsedTime="False"
            ShowStatusBar="True"
            VerticalGridLinesBrush="LightGray">
            <g:FilterDataGrid.Background>
                <LinearGradientBrush StartPoint="0.5,0" EndPoint="0.5,1">
                    <GradientStop Color="AliceBlue" />
                    <GradientStop Offset="1" Color="#FFF7EFEF" />
                </LinearGradientBrush>
            </g:FilterDataGrid.Background>

            <g:FilterDataGrid.Columns>
                <g:DataGridTextColumn
                    Width="100"
                    Binding="{Binding Path=Effective, StringFormat=d}"
                    ElementStyle="{StaticResource CenterCell}"
                    Foreground="Black"
                    Header="Effective" />
                <g:DataGridTextColumn
                    Width="75"
                    Binding="{Binding Path=Code}"
                    ElementStyle="{StaticResource LeftCell}"
                    FontWeight="SemiBold"
                    Foreground="DarkRed"
                    Header="Code" />
                <g:DataGridTextColumn
                    Width="250"
                    Binding="{Binding Path=Brand}"
                    ElementStyle="{StaticResource LeftCell}"
                    FontWeight="SemiBold"
                    Foreground="Black"
                    Header="Brand Name" />
                <g:DataGridTextColumn
                    Width="auto"
                    Binding="{Binding Path=Available, StringFormat='#,###'}"
                    ElementStyle="{StaticResource RightCell}"
                    FontWeight="SemiBold"
                    Foreground="DarkCyan"
                    Header="Available" />
                <g:DataGridTextColumn
                    Binding="{Binding Path=Size}"
                    ElementStyle="{StaticResource RightCell}"
                    Header="Size" />
                <g:DataGridTextColumn
                    Binding="{Binding Path=CasesPerPallet}"
                    ElementStyle="{StaticResource RightCell}"
                    Header="Cases Per Pallet" />
                <g:DataGridTextColumn
                    Binding="{Binding Path=SupplierAllotment}"
                    ElementStyle="{StaticResource RightCell}"
                    Header="Supplier Allotment" />
                <g:DataGridTextColumn
                    Width="200"
                    Binding="{Binding Path=BrokerName}"
                    ElementStyle="{StaticResource LeftCell}"
                    FontWeight="SemiBold"
                    Foreground="DarkMagenta"
                    Header="Broker Name" />

            </g:FilterDataGrid.Columns>
        </g:FilterDataGrid>

**Comment by mattcarlucci** [comment]
After Adding the Style included in the example, the columns appear. I'll assume it's required and there is no default style.

Step 1: App.xaml
 <Style
            x:Key="FilterDatagridStyle"
            BasedOn="{StaticResource {ComponentResourceKey TypeInTargetAssembly=control:FilterDataGrid,
                                                           ResourceId=FilterDataGridStyle}}"
            TargetType="{x:Type control:FilterDataGrid}">
            <Setter Property="Margin" Value="10,0,0,0" />
            <Setter Property="AlternatingRowBackground" Value="WhiteSmoke" />
            <Setter Property="AlternationCount" Value="2" />
            <Setter Property="ColumnWidth" Value="*" />
            <Setter Property="HorizontalGridLinesBrush" Value="LightGray" />
            <Setter Property="VerticalGridLinesBrush" Value="LightGray" />
            <Setter Property="VerticalScrollBarVisibility" Value="Visible" />
            <Setter Property="VirtualizingStackPanel.IsVirtualizing" Value="True" />
            <Setter Property="BorderBrush" Value="LightSlateGray" />
            <Setter Property="BorderThickness" Value="1" />
            <Setter Property="IsReadOnly" Value="True" />
            <Setter Property="RowHeaderWidth" Value="40" />
        </Style>

Step 2:
Add Style to all referenced grids.

**Comment by VashBaldeus** [comment]
Any advise I have tried your suggestion (using MahApps Metro) and done the style and passed it over to the grid. The Grid shows up up but does not work when I try to filter. 

Things I found:

- If you assign `Width` as `*`, menu does not show up at all.
- If you assign a numeric value to `Width`, you get the following error: https://i.imgur.com/rGWvJNa.png

**Comment by macgile** [comment]
Hi VashBaldeus,

About styling, I noticed this bug and fixed it in version 1.2.7.

For pop-up location fix, I will test your solution and implement it in the current version :)

Thank you for your contribution :)

Best regards
