### ISSUE TITLE
Bug with DataTemplate

### ISSUE THREAD

**Issue by MrPlow254** [macgile/DataGridFilter#91]
**Scope:**
It appears that when DataGridTemplateColumn.CellTemplate is in use the filter freezes and no longer functions.

```
<control:DataGridTemplateColumn Header="Collection" MinWidth="65" Width="10*" MaxWidth="150" IsColumnFiltered="False">
    <DataGridTemplateColumn.CellTemplate>
        <DataTemplate>
            <TextBlock x:Name="Collection" Text="{Binding Collection, Mode=OneWay}" MouseDown="DataGridTextColumn_MouseDown"></TextBlock>
        </DataTemplate>
    </DataGridTemplateColumn.CellTemplate>
</control:DataGridTemplateColumn>
```

**The cause:**
FieldName and SortMemberPath are not set. Probably should have a default value set somewhere to prevent the app filter from crashing. Possibly get the type of the binding variable and auto set the fieldname, and pull the datacontext/source from the textblock or its parent and auto set the sort member path.
<control:DataGridTemplateColumn Header="MCN" MinWidth="65" Width="10*" MaxWidth="150" IsColumnFiltered="True" FieldName="Collection" SortMemberPath="Collection">

**Comment by macgile** [comment]
Hi,
you have to provide the field name in DataGridTemplateColumn, it's specifically stated in the documentation otherwise it doesn't work.
FieldName property of DataGridTemplateColumn is required

<control:FilterDataGrid.Columns>   
    <control:DataGridTemplateColumn IsColumnFiltered="True"
                             FieldName="LastName" ... />

Best regards

**Comment by MrPlow254** [comment]
File: [FilterDataGrid.cs line 1229](https://github.com/macgile/DataGridFilter/blob/main/FilterDataGrid.Net/FilterDataGrid.cs#L1228) is the issue. The popup is locked as open and never closes. This code change will allow for the filter to still work even though the fieldName is empty.
`if (string.IsNullOrEmpty(fieldName)) {
    popup.IsOpen= true;
    return;
}`

**Comment by MrPlow254** [comment]
I was thinking about it more. An alternative would be to add throw new exception (e.g. ArgumentNullException) on that line instead of popup.IsOpen. If the intent is to ensure that the developer is aware of the requirement for the FieldName to be added to WPF.

The initial one i provided is essentially a silent error handling to allow for the rest of the DataGrid to still function.

**Comment by macgile** [comment]
Hi MrPlow254,

I finally understood your request (see [#95 ](https://github.com/macgile/DataGridFilter/issues/95))

**Comment by macgile** [comment]
I tried to embed an "intellisense" notification to point out the required field but couldn't find a way to make it work. It would have been more elegant.
