### ISSUE TITLE
Feature request: Nested objects within the parent collection object filtering

### ISSUE THREAD

**Issue by MrPlow254** [macgile/DataGridFilter#92]
Currently collections only show a filter by the toString() override that is within the collection. If the same collection is used twice in the datagrid that would make it useless. It would be nice to add nested collections in the filter by the value of the property within the collection at an unknown depth. I have provided a partial working solution. I haven't vetted out the actual filtering of the Items in the datagrid so this will not work with just the following code.

Code for [FilterHelpers](https://github.com/macgile/DataGridFilter/blob/main/FilterDataGrid.Net/FilterHelpers.cs#L138)
```
public static Object GetPropValue(this Object obj, String name)
{
    foreach (String part in name.Split('.'))
    {
      if (obj == null) { return null; }

      Type type = obj.GetType();
      PropertyInfo info = type.GetProperty(part);
      if (info == null) { return null; }

            obj = info.GetValue(obj, null);
        }
        return obj;
 }

public static T GetPropValue<T>(this Object obj, String name) {
    Object retval = GetPropValue(obj, name);
    if (retval == null) { return default(T); }

    // throws InvalidCastException if types are incompatible
    return (T) retval;
}
```

Code for [FilterDataGrid Line1270](https://github.com/macgile/DataGridFilter/blob/main/FilterDataGrid.Net/FilterDataGrid.cs#L1270)
```
.Select(item => Extensions.GetPropValue(item, fieldName))
```

**Comment by macgile** [comment]
Hi MrPlow254,

I don't understand what you want to do? have you implemented this before and does it work?

**Comment by MrPlow254** [comment]
I implemented the above code, but I do not have time currently to investigate further on how to implement it.
Adding this would allow for the "FieldName" to contain "Home.Room.Door.Color" Obviously none of those properties can contain any sort of array and must be a single object. I also misnamed the title I should have said nested objects within the collection (will update). Currently "SortMemberPath" works as intended to sort the collection by Color in the example earlier. However, the list provided to sort by will only show the object overload ToString method that is defined in it's class.

**Comment by macgile** [comment]
I understand better, this is how dates work with a hierarchical collection (year, month, day)

**Comment by macgile** [comment]
Hi MrPlow254,

I finally understood your request (see [#95 ](https://github.com/macgile/DataGridFilter/issues/95))

**Comment by macgile** [comment]
Hi MrPlow254,

I finally understood your request (see [#95 ](https://github.com/macgile/DataGridFilter/issues/95))
