### ISSUE TITLE
Pop up filter's background become transparent when use Page then navigate it inside Frame

### ISSUE THREAD

**Issue by ahmadun** [macgile/DataGridFilter#93]
I try to use it on Page, but when I navigate the page into Frame, the pop up filter background is going to transparent

**Comment by ahmadun** [comment]
Pop up

**Comment by macgile** [comment]
can you provide a screenshot

**Comment by ahmadun** [comment]
![image](https://user-images.githubusercontent.com/20293422/212696768-c1e142d9-5076-4902-9edb-262572ee5fc7.png)

Here is my code, to open the Page
` private void UserControl_Loaded(object sender, RoutedEventArgs e)
        {
            MainWindow page = new MainWindow();
            frag.Navigate(page);
        }`

**Comment by ahmadun** [comment]
Currently to solve it, I change background the border here, then compile the project so I can use dll file
`
![image](https://user-images.githubusercontent.com/20293422/212697745-e62bc0cd-d47d-4cbe-8186-9af205541148.png)
`

**Comment by macgile** [comment]
The style of the popup may not be suitable in certain conditions, especially in the choice of colors.
