### ISSUE TITLE
Search pop up does not get any values?

### ISSUE THREAD

**Issue by VashBaldeus** [macgile/DataGridFilter#94]
Current XAML:
```xaml
<filterDataGrid:DataGridTextColumn IsColumnFiltered="True" Width="*"
		Header="Model" Binding="{Binding Model.Vehicle_Name}"/>
<filterDataGrid:DataGridTextColumn IsColumnFiltered="True" Width="*"
		Header="Mod Vehicle" Binding="{Binding Model.Vehicle_IsMod, Converter={StaticResource YesNoConverter}}"/>
```
in both cases that is how the column search looks like:
![screenshot of issue](https://i.imgur.com/LN5iWLL.png)

It works normally only if the bound value is not part of a class/model

**Comment by macgile** [comment]
```xaml
<filterDataGrid:FilterDataGrid
            ItemsSource="{Binding Model, UpdateSourceTrigger=PropertyChanged}">
<filterDataGrid:FilterDataGrid.Columns>
<filterDataGrid:DataGridTextColumn IsColumnFiltered="True" Width="*"
		Header="Model" Binding="{Binding Vehicle_Name}"/>
```

**Comment by VashBaldeus** [comment]
> ```
> <filterDataGrid:FilterDataGrid
>             ItemsSource="{Binding Model, UpdateSourceTrigger=PropertyChanged}">
> <filterDataGrid:FilterDataGrid.Columns>
> <filterDataGrid:DataGridTextColumn IsColumnFiltered="True" Width="*"
> 		Header="Model" Binding="{Binding Vehicle_Name}"/>
> ```

So no way of incorporating Converters either.

**Comment by macgile** [comment]
Other users have raised the issue of nested objects and offered a solution.
For the moment this solution poses a lot of problem and I cannot implement it without having solved them.
Follow these requests :

[](https://github.com/macgile/DataGridFilter/issues/92)
[](https://github.com/macgile/DataGridFilter/issues/95)
