### ISSUE TITLE
Incorrect Chinese sorting

### ISSUE THREAD

**Issue by easyboot** [macgile/DataGridFilter#98]
![image](https://user-images.githubusercontent.com/26960023/217758951-176e12e2-cf79-422c-b8f8-92ce09f2b2bc.png)

After upgrading to 1.2.7, I found that the Chinese collation is different from 1.2.5. The new sorting method is incorrect

**Comment by easyboot** [comment]
![image](https://user-images.githubusercontent.com/26960023/217763888-301393c9-44fb-40bc-8240-dc99fec873ed.png)

**Comment by macgile** [comment]
The sort methods in Filter DataGrid are the native methods of the DataGrid. 
My native language is not Chinese, I don't understand what you mean despite the screenshots you provided.
I may be able to help you but for that please be more explicit

**Comment by easyboot** [comment]
In 1.2.5, Chinese is sorted according to ascii code, but in 1.2.7, this rule is not followed. The numbers in my example should be in front of Chinese

**Comment by easyboot** [comment]
![image](https://user-images.githubusercontent.com/26960023/217977646-ab677146-fdfd-4364-9038-76190a4d6d30.png)
If the code in the figure is not masked here, my program's first assignment of ItemsSource="{Binding FilterDGList}" is correct, and the second assignment will cause binding errors. If I mask this sentence, it can be assigned normally.

**Comment by macgile** [comment]
Hi, 
It's strange because I didn't change the sorting method for the popup list !
